### ISSUE TITLE
displayed source of ++malt seems broken

### ISSUE THREAD

**Issue by frunjik** [urbit/urbit.org#1010]
The source of ++malt shown on
https://urbit.org/docs/reference/library/2l/#malt
seems broken

**Comment by tinnus-napbus** [comment]
seems to work fine for me and it matches what's in hoon.hoon, I think there's no problem here

```
> =a |*  a=(list)
  (molt `(list [p=_-<.a q=_->.a])`a)
> (a [['ok' 'no'] ['a' 'b'] ['x' 'y'] ~])
[n=[p='x' q='y'] l={[p='a' q='b'] [p='ok' q='no']} r={}]
```
