### ISSUE TITLE
+* no longer documented in Hoon school

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#1013]
With urbit/docs#900 we no longer discuss `+*` in Hoon school. Previously we had only discussed it in the context of type polymorphism, but as that usage has been taken over by `|$`.

Now the only two spots that `+*` are mentioned in Hoon school is in code used in `gall.md` and `egg-timer.md`, where it is used as `+*  this  .`. `+*` is confusing enough that I don't think we should use it without explaining it.

**Comment by tinnus-napbus** [comment]
hoon school has been rewritten and no longer touches on gall agents. Lustar is now covered in the gall guide
