### ISSUE TITLE
revise hoon school lesson on ford

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#1017]
The long anticipated Ford Fusion arrived with urbit-os-v1.0.24, and with it comes necessary revision to our documentation.

The most pressing one in terms of how much it is probably used by the community is the Hoon school lesson on Ford at `/tutorials/hoon/ford.md` and unit tests at `tutorials/hoon/test-sets.md`. Since I wrote these lessons and plan to write Clay documentation this quarter, this seems to naturally fall to me.

**Comment by tinnus-napbus** [comment]
hoon school has now been fully rewritten
