### ISSUE TITLE
Reorganize tutorials folder structure

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#1026]
We've slowly been accumulating Hoon tutorials that don't quite fit into the current folder structure.

The worst offender at the moment is the parsing tutorial, which currently lives under the /arvo folder.

The main problem I see, though, is that /hoon is entirely for Hoon school at the moment, leaving no sensible place for Hoon tutorials that aren't a part of Hoon school. I think just making a /hoon-school folder under /hoon and putting other Hoon tutorials (like parsing) under /hoon is sensible. This is a very easy change to make but altering the folder structure should be done sparingly and with careful consideration of future needs so this would benefit from multiple people weighing in.

We discussed the issue briefly at the docs meeting last week and @vvisigoth said to hold off on reorganizing right then, but I've forgotten the reason he said at this point. Care to weigh in?

**Comment by urcades** [comment]
@drbeefsupreme this is exciting, has been long in the tooth
