### ISSUE TITLE
portable snapshots in new vere

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#1033]
From the release notes for the pending new vere release:

- Portable snapshots

 You can now create and boot from portable snapshots of your urbit's persistent
 state. For example, `urbit -n 200 path/to/pier` will replay up to event `200`,
 then write the resulting state to `path/to/pier/.urb/roc/200.jam`. To then
 boot from the created snapshot, `urbit -r 200 path/to/pier`. These options
 can be combined to perform granular event log replay.
 Their functionality is also available directly through `urbit-worker`, as
 `urbit-worker cram path/to/pier` and `urbit-worker queu path/to/pier`
 respectively.

**Comment by tinnus-napbus** [comment]
this is now documented in the new vere reference
