### ISSUE TITLE
document |meld

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#1034]
From the release notes for the pending new vere:

- `|meld`, global state deduplication

 Previously, `|pack` would let you initiate memory compaction, deduplicating
 all of your urbit's persistent state to ensure minimal memory usage. But this
 would fail if you did not have enough available memory to complete the
 process. `|meld` reimplements this using `ur` (discussed above). It copies
 your urbit's state out of its memory, deduplicates it, and replaces your
 urbit's memory with the result, avoiding the failure case that `|pack` used
 hit.
 In addition to `|meld` in dojo, you may also invoke this on a ship that is
 not running using `urbit-worker meld path/to/pier`.
 (Note that this may use a lot of system memory, and so might be slow or not
 complete at all on machines with little RAM.)

**Comment by tinnus-napbus** [comment]
this is now documented in the vere reference
