### ISSUE TITLE
Can't scroll menu

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#104]
<img width="875" alt="Screenshot 2019-05-23 22 36 3" src="https://user-images.githubusercontent.com/31774/58304927-2d09b000-7dab-11e9-8d1d-26dd19aabc6f.png">

Menu can't scroll if the window isn't big enough to show all the content.

**Comment by hardcodepunk** [comment]
This issue has been addressed and fixed in the `general-bug-fixes` branch.
