### ISSUE TITLE
hoon standard library docs need some love

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#1040]
I don't know when the stdlib docs were first written but I encounter something wrong with it probably around once a month. Somebody needs to go through the whole thing, page by page, and make sure its all still up to date.

That would be a long and arduous task though, and wouldn't solve the problem of it going out of date forever. A better solution would be to import code automatically - something we've wanted to have for awhile but is lost among too many other priorities - along with docstrings. I remember @rmariani was working on docstrings support earlier this year but I don't remember if he had a chance to finish it (or maybe it was @baudtack).

In the meantime, I encourage you to use this thread to post individual issues with the standard library docs. I'm fine with handling them ad-hoc until we can generate them automatically, as individual fixes usually take less than 5 minutes.

Per @joemfb this effort would also be greatly assisted by real Kelvin versioning for the standard library

**Comment by tinnus-napbus** [comment]
stdlib reference now up to date
