### ISSUE TITLE
Site could use some left-padding

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#105]
<img width="594" alt="Screenshot 2019-05-23 22 39 43" src="https://user-images.githubusercontent.com/31774/58305103-bb7e3180-7dab-11e9-97d5-c15b8ed9dba5.png">
<img width="325" alt="Screenshot 2019-05-23 22 39 57" src="https://user-images.githubusercontent.com/31774/58305105-bb7e3180-7dab-11e9-990a-126024617c65.png">

Navigation and menu button get pushed up right to the left edge. Could use a little left-padding at these sizes.

**Comment by hardcodepunk** [comment]
Added some padding-left on these elements in the `general-bug-fixes` branch.
