### ISSUE TITLE
Ford runes no longer work in dojo

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit.org#1055]
The dojo docs, in [the variables section](https://urbit.org/using/operations/using-your-ship/#variables) shows examples of using the `/-` and `/+` ford runes.

This no longer works. You have to use the `-build-file` thread like `=builtlib -build-file %/lib/mylib/hoon` and then you can use `your-arm:builtlib`

**Comment by tinnus-napbus** [comment]
ford runes are no longer mentioned in the variables section
