### ISSUE TITLE
Deprecated arms `+my` and `+sy` are still littered around in example code

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit.org#1066]
According to @tacryt-socryp , `+my` and `+sy` are deprecated in favor of `+malt` and `+silt`.

**Comment by tinnus-napbus** [comment]
examples no longer use `my`/`sy` afaik

**Comment by joemfb** [comment]
Huh, I wonder where @tacryt-socryp got that from ... `+my` and `+sy` are both newer implementations, and more general (wrt type inference over heterogenous elements) than `+malt` and `+silt`:

```
> (silt %foo %bar ~)
-need.?(%~ [i=%foo t=it(%foo)])
-have.[i=%foo t=[i=%bar t=%~]]
nest-fail
dojo: hoon expression failed
> (sy %foo %bar ~)
[n=%bar l={} r={%foo}]
```

(FWIW, I'm not a big fan of any of the "casual constructors", and prefer to just use `+gas:in` or `+gas:by`.)

**Comment by tacryt-socryp** [comment]
Compilation takes much longer for `+my` and `+sy`

**Comment by joemfb** [comment]
Yeah, that's one of several reasons to prefer the more explicit types of the `+gas` arms.
