### ISSUE TITLE
Hooniversity links to development docs are broken.

### ISSUE THREAD

**Issue by thelifeandtimes** [urbit/urbit.org#1067]
The links in the hooniversity lessons go to a '404 page not found'. The proper resources can be found relatively easily via search, but could be worth updating. 
example: 
hooniversity link to the hoon style guide: https://urbit.org/docs/tutorials/hoon/style/
actual link to the hoon style guide: https://urbit.org/docs/hoon/reference/style/

**Comment by drbeefsupreme** [comment]
You must have an old version of urbit.org. Try clearing your cache? There is no link to https://urbit.org/docs/tutorials/hoon/style/ anywhere on urbit.org right now.
