### ISSUE TITLE
whitespace in codeblocks in urbit.org not rendering properly 

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#1081]
See e.g. https://urbit.org/docs/hoon/reference/style - the rune fanouts in the tall form section are missing two spaces on the first child for 3- and 4- child runes. These spaces do exist in the markdown, so its a problem with urbit.org. There's probably other examples on the site, I'd guess wherever there's 4+ spaces. EDIT: nope, see below

**Comment by drbeefsupreme** [comment]
Since this might be browser/OS specific, I should mention that this is in Brave running on Linux.

**Comment by drbeefsupreme** [comment]
Ok it looks like the renderer is ignoring the leading white space at the start of the code block. I've fixed the style page for now by just left shifting all the code blocks so they don't start with white space, but it would be better for it to render properly.

**Comment by g-a-v-i-n** [comment]
Could you post a link to an example?

**Comment by g-a-v-i-n** [comment]
How should these look?

**Comment by drbeefsupreme** [comment]
```
!:
a
```
```
=+  a
b
```

```
?:  a
  b
c
```
```
:^    a
    b
  c
d
```

**Comment by drbeefsupreme** [comment]
Should note that I haven't actually merged my fix yet so the issue still exists in the link in the OP (urbit.org isn't compiling atm and I haven't checked why yet)

**Comment by g-a-v-i-n** [comment]
#1087 should resolve this

**Comment by drbeefsupreme** [comment]
thanks!
