### ISSUE TITLE
grants page

### ISSUE THREAD

**Issue by h5gq3** [urbit/urbit.org#1099]
Remove "Similar Grants" section below each grant

**Comment by g-a-v-i-n** [comment]
Can you elaborate?

**Comment by h5gq3** [comment]
1. the grants showing there aren't similar at all
2. why even need filtering by similarity? this metric for filtering is very
ambiguous

i'm just nitpicking. makes me wonder if this was generated by a template lol

**Comment by g-a-v-i-n** [comment]
these are all good reasons

**Comment by jalehman** [comment]
This has been taken care of. Thanks for flagging @h5gq3
