### ISSUE TITLE
Lingering references to the now-defunct discord server :cry:

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit.org#1101]
A quick search yields these 4 so far:

- https://github.com/urbit/urbit.org/blob/c79b4f4d44ca8e853e3a4e67abdb4fb6f9dfb71f/lib/constants.js#L6
- https://github.com/urbit/urbit.org/blob/c79b4f4d44ca8e853e3a4e67abdb4fb6f9dfb71f/components/Contact.js#L84-L86
- https://github.com/urbit/urbit.org/blob/7115a0cf8fb11c0099b49002091b8cb17182318b/content/using/id/guide-to-breaches.md#breaches
- https://github.com/urbit/urbit.org/blob/94c876d2988f5d45c391a6cb429b78c6468248a5/content/using/os/ship-troubleshooting.md#perform-a-personal-breach-personal-breach

This is excluding historical references in past grants.

**Comment by g-a-v-i-n** [comment]
Resolved in #1118
