### ISSUE TITLE
codeblocks have started rendering as v. long inline code

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit.org#1109]
![2021-09-09_18h43m20s](https://user-images.githubusercontent.com/77721746/132636099-7e4f9e2d-483c-4462-81d2-edcedec4ea38.png)

**Comment by tinnus-napbus** [comment]
CC @g-a-v-i-n I think?

**Comment by g-a-v-i-n** [comment]
Could you paste the file source please?

**Comment by tinnus-napbus** [comment]
https://urbit.org/docs/hoon/reference/stdlib/3c#user-content-yule

https://github.com/urbit/urbit.org/blame/master/content/docs/hoon/reference/stdlib/3c.md#L301-L326

all triple-backticked codeblocks render the same way

Edit: sorry should have clarified it's markdown codeblocks, not html

**Comment by g-a-v-i-n** [comment]
Resolved in #1117

The issue was Vercel was installing deps with yarn instead of npm.

**Comment by g-a-v-i-n** [comment]
Resolved in #1117

This bizarre issue was due to Vercel installing deps with yarn instead of npm.
