### ISSUE TITLE
getting started CLI page doesn't display mac/linux heading

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#1113]
It just shows the instructions for each one after the other. At least in Brave and Chrome. The code is there, its just not displaying for some reason.

https://urbit.org/getting-started/cli

https://github.com/urbit/urbit.org/blob/master/content/getting-started/cli.md

**Comment by g-a-v-i-n** [comment]
This is puzzling me quite a bit

**Comment by g-a-v-i-n** [comment]
Resolved in #1117

This bizarre issue was due to Vercel installing deps with yarn instead of npm.
