### ISSUE TITLE
hoon syntax highlighting not working

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit.org#1119]
@g-a-v-i-n The vercel dependency thing appears to have fixed codeblock rendering and some other things, but there doesn't seem to be hoon syntax highlighting anymore

local dev version looks like:

![2021-09-12_15h48m29s](https://user-images.githubusercontent.com/77721746/132971385-5856f8f3-b673-4c78-8f73-6499920a5c21.png)

but urbit.org looks like:

![2021-09-12_15h48m40s](https://user-images.githubusercontent.com/77721746/132971392-24f82b77-9b50-4882-953c-0a663672734e.png)

Edit:

these are markdown codeblocks like:

\`\`\`hoon
[some code]
\`\`\`

**Comment by g-a-v-i-n** [comment]
Looks like syntax highlighting is working for C
https://urbit.org/docs/vere/c

I suspect this has to do with the patched remark-prism situation

**Comment by g-a-v-i-n** [comment]
Resolved in #1122
