### ISSUE TITLE
Bullets seem to break mid-paragraph

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit.org#1133]
See https://urbit.org/docs/arvo/concepts/subscriptions for an example of this.

Screenshot
![image](https://user-images.githubusercontent.com/9275716/133689229-82f96f3e-3f7f-415c-8b8b-19b65095d391.png)

Offending lines:
https://github.com/urbit/urbit.org/blob/d0f5630576f2a97d792ec3552360ef49b017fbe1/content/docs/arvo/concepts/subscriptions.md#L78-L92

It looks like whatever is parsing the markdown is treating double spaces in the content as a newline, weirdly enough.

**Comment by tinnus-napbus** [comment]
it seems to be unaffected by double spaces or not. It's fixed by indenting the subsequent lines to match the first, see the mentioned PR above.

this seems to be non-standard markdown list parsing behaviour compared to other implementations, unsure if bug or just a difference though

**Comment by matildepark** [comment]
Since this issue we moved Markdown parsers, re-open if persists.
