### ISSUE TITLE
wrapped section titles in contents sidebar indistinct

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit.org#1135]
section headings which are too wide get wrapped in the auto-generated contents sidebar thing, but their line spacing/padding/whatever is identical to the spacing between separate sections. This makes it unclear at a glance that the two lines are a single thing as opposed to two separate sections.

Eg:

![2021-09-18_03h19m41s](https://user-images.githubusercontent.com/77721746/133808446-02378027-2bca-4b49-86e6-21e8e93fe95e.png)

It would be cool if the line spacing or whatever were smaller (or otherwise visually distinct) for wrapped section headings so it's clear they're one thing.

@g-a-v-i-n 

Edit: These pages have live examples:

https://urbit.org/docs/arvo/tutorials/move-trace
https://urbit.org/docs/arvo/eyre/examples

**Comment by g-a-v-i-n** [comment]
This UI needs to be updated regardless
