### ISSUE TITLE
Suggestion: Refactor `urbit.org/docs/azimuth` for increased clarity of the technical elements of our smart contract

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#1136]
Today, I was trying to find some basic statistics on our token/smart contract, such as the breakdown of point types, the contract address, etc. and couldn't really come up with anything straightforward on the page that's supposedly describing a smart contract system named Azimuth!

At the top of the page, we should list out plainly in a table or list some of the basic details of the system.

Things like:

- The max supply of the total namespace
- The breakdown of how many Urbit IDs of a specific type exists
  - number of Galaxies
  - number of Stars
  - number of Planets
- The contract address
- etc.

This doesn't need to be be overthought or made into something fancy, we simply need to expose these details and spell them out when one searches for "Azimuth" on the site.

Some of the more data-oriented sections of this page are a good example of what should he immediately highlighted:

https://uniswap.org/blog/uni/

**Comment by drbeefsupreme** [comment]
Thanks, I will roll this into #1084 , please feel free to make other suggestions for the Azimuth docs since I'm taking this opportunity to look over all of them.
