### ISSUE TITLE
markdown codeblocks have regressed to very long inline style again

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit.org#1139]
See eg: https://urbit.org/docs/hoon/reference/stdlib/1b#user-content-cap

@g-a-v-i-n

**Comment by g-a-v-i-n** [comment]
For some reason, parts of the markdown processing chain are not running. It seems to depend on node version, webpack version and next version.

**Comment by drbeefsupreme** [comment]
Probably the same issue - the first line in a code block has additional spaces at the front.

see e.g.

https://urbit.org/docs/hoon/reference/style

vs the markdown

```
:^    a
    b
  c
d
```

**Comment by jamesacklin** [comment]
Have a hunch that remark-prism isn't working properly, but at least getting the blocks themselves styled properly.

Before:
![image](https://user-images.githubusercontent.com/748181/135009757-da7a038e-9b68-433b-af7f-c37b2a6c8584.png)

After: 
![image](https://user-images.githubusercontent.com/748181/135009742-2dd32413-ea64-47bf-a36d-aef605c8446e.png)
