### ISSUE TITLE
image embeds not appearing when they're html tags in markdown files

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit.org#1160]
See:

https://urbit.org/docs/userspace/graph-store/validator-walkthrough

vs:

https://github.com/urbit/urbit.org/blame/master/content/docs/userspace/graph-store/validator-walkthrough.md#L26-L28

I assume this is related to the other issues with codeblocks and section links and such

**Comment by g-a-v-i-n** [comment]
yes, I think this is related to the markdown chain

**Comment by tinnus-napbus** [comment]
fixed by #1189
