### ISSUE TITLE
Need definition for master ticket

### ISSUE THREAD

**Issue by baudtack** [urbit/urbit.org#1164]
We need a definition of master ticket on the site. A number of new users into bridge are confused by what this is and try to transfer to it even though they don't need to.

**Comment by drbeefsupreme** [comment]
I have already done this in #1084 but there's probably still more clarity I could add.

**Comment by baudtack** [comment]
looks pretty good! docs team on point.

Specifically though we should provide some guidance on when/if you should transfer to a master ticket as a lot of people seem to just... try to do that to "fix" whatever problem they are having and all it's doing is confusing them and costing them money.

**Comment by drbeefsupreme** [comment]
#1084 doesn't quite cover this

**Comment by matildepark** [comment]
It shows in search, links to https://operators.urbit.org/manual/id/hd-wallet
