### ISSUE TITLE
FAQ: Superscript missing

### ISSUE THREAD

**Issue by lidreg-dillut** [urbit/urbit.org#1193]
Hello,

A small observation: on the FAQ page, superscripts do not render, so the section on address space is somewhat nonsensical (see screenshot). 

<img width="380" alt="superscript" src="https://user-images.githubusercontent.com/82872640/136380812-4ed764b5-7e45-4c9e-b0ba-44e9170dd0b2.png">

The superscript tags appear in the markdown source for the page, but something in the rendering pipeline appears to strip them out. Unfortunately, I don't know enough about the engine you're using to have any idea why.

Cheers!

**Comment by drbeefsupreme** [comment]
Yeah this is probably part of the general issue that the site is currently having with markdown. This is also already covered by #1153
