### ISSUE TITLE
Partial results don't match in search

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#124]
Perhaps this is by-design, or hard to do, but partial matches don't seem to work.

<img width="923" alt="Screenshot 2019-06-14 17 2 27" src="https://user-images.githubusercontent.com/31774/59544431-468faa80-8ec6-11e9-9e8b-0641d6a933cd.png">

**Comment by flowerornament** [comment]
Interestingly, "contribut" produces results, but "contributi" doesn't.

I'm wondering if maybe this is a feature though ... if partial matches were admitted, they might overwhelm exact matches in the search results. Don't understand well enough how this works to know.

**Comment by hardcodepunk** [comment]
Neither do the Zola (https://www.getzola.org/) or Elasticlunr website search (http://elasticlunr.com/example/index.html) have this functionality.
This is not a feature in the current elasticlunr implementation in Zola either. Elasticlunr uses a stemmer. So 'contribut' might be linked to contribute or something, but for some reason contributi doesn't get recognized. The stemmer of Elasticlunr: http://elasticlunr.com/docs/stemmer.js.html

The actual elasticlunr port to Rust which's been used by Zola if I'm correct: https://github.com/mattico/elasticlunr-rs

Here's info about partial matching in Lunr: https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-matching.html

I did find a search-as-you-type feature: https://www.elastic.co/guide/en/elasticsearch/guide/current/_index_time_search_as_you_type.html
Kind of an autocomplete feature. Would you like to have this implemented?

**Comment by flowerornament** [comment]
@friederjanmoerman it would be nice, but I think low-priority. Thanks for looking into this.

**Comment by flowerornament** [comment]
closing for now – we can implement this later if desired
