### ISSUE TITLE
Remove posts from search index

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#125]
Testing in Safari.

Reproduce by searching for "%clay" or "clay"

- Search reports 34 matches, but displays a single result
- There are ~110 instances of "clay" on that single page (not sure if that 34 is total matches or total matched pages)
- "clay" appears elsewhere throughout the docs: https://www.google.com/search?q=site%3Aurbit.org%2Fdocs+clay, but those pages aren't returned

<img width="630" alt="Screenshot 2019-06-18 16 4 54" src="https://user-images.githubusercontent.com/31774/59725553-dabd8280-91e2-11e9-82d2-b9b181b03731.png">

**Comment by flowerornament** [comment]
Fixing this requires excluding posts from the searching index.

**Comment by hardcodepunk** [comment]
Posts have been removed from the index of the **search-bar-release** branch by putting `in_search_index = false` in the front matter of `posts/_index.md` (make sure you restart the `zola serve` process to rebuild the search index to apply the changes you make).
