### ISSUE TITLE
Test and upgrade to zola 0.8

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#126]
urbit.org is now running a pretty old version of zola. 0.6 and 0.7 had fatal build bugs – hopefully this works: https://github.com/getzola/zola/releases/tag/v0.8.0

**Comment by hardcodepunk** [comment]
Run `brew upgrade zola` to update. Build/serve tested and no errors ocurred. Didn't find any bugs at first sight.

**Comment by flowerornament** [comment]
Awesome – you can bump the version here: https://github.com/urbit/urbit.org/blob/master/netlify.toml and in the README

**Comment by flowerornament** [comment]
Done in https://github.com/urbit/urbit.org/pull/136
