### ISSUE TITLE
RSS feed lacks heaps of content

### ISSUE THREAD

**Issue by tlon-gh-bot** [urbit/urbit.org#127]
<a href="https://github.com/allanhortle"><img src="https://avatars1.githubusercontent.com/u/3760524?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [allanhortle](https://github.com/allanhortle)**
_~2018.01.24..21.43.02_
_Originally opened as https://github.com/urbit/fora/issues/4_

----

I'd love to keep track of what's going on with Urbit via RSS but it's really hard.

* The rss feeds lack any meta data.
* They are often out of order. 
* They hold no content. 

Both fora and urbit.org have the same issues.
https://fora.urbit.org/posts.rss-xml
https://urbit.org/blog.rss-xml

![image](https://user-images.githubusercontent.com/3760524/35358576-34717d8c-01ab-11e8-8392-212ff7f5f5eb.png)

```xml
<rss version="2.0">
    <script/>
    <channel>
        <title/>
        <link>https://urbit.org/posts</link>
        <description/>
        <item>
            <title/>
            <description/>
            <link>
                https://urbit.org/posts/~2016.9.28..17.57.25..6a50~
            </link>
        </item>
        <item>
            <title/>
            <description/>
            <link>
                https://urbit.org/posts/~2017.5.22..23.06.51..9394~
            </link>
        </item>
...
```

**Comment by joemfb** [comment]
This issue definitely referred to the rss implementation in the `&rss-xml` mark. Which is still in arvo, but no longer used as far as I know. That urbit.org RSS feed looks fine at a glance.

**Comment by francescanarea** [comment]
@joemfb Are you referring to the rss-xml.hoon transformer in arvo?

**Comment by flowerornament** [comment]
Thanks for this. For current urbit.org, we need to create an RSS template as per https://www.getzola.org/documentation/templates/rss/.

**Comment by joemfb** [comment]
@francescanarea, that's right.

**Comment by flowerornament** [comment]
@friederjanmoerman want to look into this?

**Comment by alexmatz** [comment]
any luck on this @friederjanmoerman? Can ask Francesca to take a look if you haven't already!

**Comment by hardcodepunk** [comment]
I'll look into it today @alexmatz

**Comment by hardcodepunk** [comment]
<img width="948" alt="Screenshot 2019-07-03 at 14 04 20" src="https://user-images.githubusercontent.com/9070957/60590162-95c94c80-9d9b-11e9-9583-0c3da0eddf88.png">

RSS template added to the `rss-template` branch. I'm no RSS feed user but tested in ViennaRSS and looks okay to me? If any features are missing, let me know and I'll look into it.

**Comment by flowerornament** [comment]
Just saw this from an RSS bot in Discord. Most recent commit upgraded to 0.8.0 and I wonder if that has something to do with it, but this is definitely undesirable behavior.

```
~2019.6.14 Update

https%3A//urbit.org/posts/2019-6-14-update/
```

**Comment by matildepark** [comment]
Put a PR in at #137.

**Comment by friederjanmoerman** [comment]
> Just saw this from an RSS bot in Discord. Most recent commit upgraded to 0.8.0 and I wonder if that has something to do with it, but this is definitely undesirable behavior.
> 
> ```
> ~2019.6.14 Update
> 
> https%3A//urbit.org/posts/2019-6-14-update/
> ```

The `%3A `? Or what exactly is undesirable?

**Comment by hardcodepunk** [comment]
> Put a PR in at #137.

@matildepark you are taking over this issue, am I right?
Or is there something you want me to do?

**Comment by matildepark** [comment]
Oh, I'm technically not on site duty — I just put in PRs if I have the bandwidth and it's low hanging fruit, usually. Do you want me to take ownership over this? I can work with @msutherl. 

Edit: Apologies @friederjanmoerman, I see [you were in the process of committing a template anyhow](https://github.com/urbit/urbit.org/commit/80899ed012f0d9735afeb7669d4477e97e2d3cf3). I'll try not to step on your toes in future.

**Comment by alexmatz** [comment]
@matildepark thank you for all of your work on Urbit! For context, I was doing some housekeeping with @friederjanmoerman as he wraps up working with us. You are welcome to take a look!

**Comment by matildepark** [comment]
Is there anything left to do for this?

**Comment by flowerornament** [comment]
@matildepark want to test with an RSS client and see if we're a-ok? Things to look for:

- RSS client can actually find the `rss.xml` file from the URL (urbit.org)
- There's one entry per post
- Each post has a title, short-description, and content
- Images show up correctly
- Older posts show up

Last time I tried this, there were a bunch of issues, but it might have been before the recent fixes.

**Comment by matildepark** [comment]
Tried in Reeder 3.

[x] Found from the URL (urbit.org)
[x] One entry per post.
[x] Each post has a title and the full content. The short description is the first line of the post.
[x] Images show correctly.
[x] Posts go back to 2016.

<img width="1212" alt="Screen Shot 2019-07-31 at 3 37 01 PM" src="https://user-images.githubusercontent.com/20846414/62242450-331e9d00-b3a9-11e9-969f-08a0648f9436.png">
<img width="1212" alt="Screen Shot 2019-07-31 at 3 37 07 PM" src="https://user-images.githubusercontent.com/20846414/62242455-36b22400-b3a9-11e9-9321-5e858534aaad.png">
<img width="1212" alt="Screen Shot 2019-07-31 at 3 37 09 PM" src="https://user-images.githubusercontent.com/20846414/62242465-3a45ab00-b3a9-11e9-8323-ea23b1c22fe3.png">

**Comment by flowerornament** [comment]
Beautiful. Looks like we're good.

**Comment by ksbrar** [comment]
Super happy to see this change. Not really sure if this is relevant on your end, but I wanted to point out that Inoreader did not seem to automatically find the RSS link (had to manually add it myself).

**Comment by matildepark** [comment]
@ksbrar Thank you for the catch! I installed Inoreader and gave it a shot, can confirm it's reproducible. I wondered if it didn't auto-find the feeds on the client side, but trying nytimes.com auto-found the feed easily. I checked nytimes.com's RSS code and the only real difference is the title and use of a *full path* whereas we use a relative path. 

I edited our code to match that. I tried to confirm it worked locally, but Inoreader seems to network request the feed outside the local network (since it's cloud-based first). Put a PR in at #164 which provides a deploy preview with a non-local URL, so I could then test it. The deploy preview's RSS linking, with the changes from the PR, is also not discoverable by Inoreader, but the PR is good to have anyway, I think.

The PR's deploy preview, however, *is* discoverable by other cloud-based services like Feedly (Urbit.org itself also is discoverable there, but if any one person added the RSS link directly, it shows everyone else that). 

I can't look at Inoreader's code to really go much further than this unfortunately.

**Comment by Fang-** [comment]
Wasn't gonna report this, but might be related: my home-grown RSS reader also can't currently find the rss.xml automatically. Doesn't work for your PR's deploy preview either. It makes use of [SimplePie](https://github.com/simplepie/simplepie/) under the hood.

**Comment by matildepark** [comment]
I see some locator logic [here](https://github.com/simplepie/simplepie/blob/f1455566e48e8df284e6d01ca0a9157b74802c9b/library/SimplePie/Locator.php#L199), I'll look into it and see what needs doing ...
