### ISSUE TITLE
`urbit.org` homepage has incorrect width, displays unnecessary horizontal scrollbar

### ISSUE THREAD

**Issue by raglep-ragret** [urbit/urbit.org#1287]
Hello all, there is currently a visual bug on [urbit.org](https://urbit.org/). This bug may not be obvious if you're on a Mac and hide scrollbars by default, but should become obvious if you are on a non-Mac or if you always show scrollbars. The problem is this:

![image](https://user-images.githubusercontent.com/93157753/147280892-3e393411-0017-4189-bf68-e66918fc87a6.png)

urbit.org *always* displays a horizontal scrollbar, even there is no content that horizontally overflows! It will do this on any screen size. As it turns out, this is do to a simple issue with `width: 100vw` that is trivial to fix. I have put in PR #1279 which fixes this bug.

**Comment by matildepark** [comment]
Closed by #1279
