### ISSUE TITLE
minor tweak: app install page should recommend different desk

### ISSUE THREAD

**Issue by aquarial** [urbit/urbit.org#1289]
https://urbit.org/docs/userspace/dist/guide#install suggests creating a new desk by `|merge %hello our %base` and then `|mount %hello`

`%base` is very big, while something like `%webterm` is rather small. It's way faster to run `|merge %hello our %webterm`. 

It's safe to switch parent desks because the next step is `rm -r hello/*` anyway.

**Comment by tinnus-napbus** [comment]
they're gonna introduce a new generator very soon that creates a skeleton desk without having to merge (see: https://github.com/urbit/urbit/pull/5360), so am just gonna wait for that before updating current merge instructions
