### ISSUE TITLE
revise references to `%home` desk

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#1304]
Some parts of the docs still talk about the `%home` desk, like `/docs/arvo/ford/ford.md`. In most cases this can just be swapped with `%base`, but some cases will require a bit more editing since `%base` is not the only desk that apps can be run from anymore, unlike how `%home` used to work.

**Comment by tinnus-napbus** [comment]
I've updated all instances throughout the docs except ford and some paths in the jetting doc. The ford doc states:

> The following is a reproduced blog post that documents this transformation, which we called "Ford Fusion".

so I think it's ok to be outdated. The ford doc should ultimately be removed and relevant info integrated into clay docs, rune reference docs and maybe a couple of other places. Until we do that I think it's ok as-is

**Comment by drbeefsupreme** [comment]
I've made some minor updates to other blog posts that turned into docs in the past. I think changing the note at the top that says something like "This is a reproduced blog post with minor changes to reflect subsequent updates." is fine. As long as the original blog post remains the same, I don't see an issue with this.

**Comment by drbeefsupreme** [comment]
Should have been closed with #1312
