### ISSUE TITLE
Swap space troubleshooting not readily available

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit.org#1327]
If the urbit process fails to map 2GB of memory during startup, it will helpfully tell you:

```
see urbit.org/using/install/#about-swap-space for adding swap space
```

...Except that link just redirects to the `/getting-started` page, which has no information at all about swap space.

The binary could be updated to give a different url, but probably better to try solving this docs-side first.

**Comment by matildepark** [comment]
See also https://github.com/urbit/urbit/issues/3627

We don't document swap space anywhere. Should we? @sigilante @gordoncc 

Even if we do add this copy, the link is going to change.

**Comment by gordoncc** [comment]
I feel like @tinnus-napbus knows or could write the docs for this.
