### ISSUE TITLE
search is swallowing stdlib glossary entries again

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit.org#1330]
this was fixed for a while but it's started happening again. When you search for e.g. `turn`, it flashes the `/lib/glossary.js` result for a second and then it disappears. If you backspace the last letter and retype it, the glossary result then correctly appears.

**Comment by matildepark** [comment]
@tinnus-napbus Can't actually replicate this on master; can you? What browser, etc.? Wonder if it's weird flexboxing, but highly unlikely.

**Comment by tinnus-napbus** [comment]
my browser is qutebrowser which uses qtwebengine which uses the chromium engine. I also tried in chromium and firefox and it does it too. It doesn't happen every time but most times it does. It's on arch linux x86_64

**Comment by tinnus-napbus** [comment]
Here's an example in chromium of it happening some times and not others:

https://m.tinnus-napbus.xyz/pub/2022.4.20..15.19.15-search-2022-04-21_03.15.54.mkv

**Comment by matildepark** [comment]
OK so, what I notice off the bat is that you get *way more* results for flip than I do — 

<img width="945" alt="image" src="https://user-images.githubusercontent.com/20846414/164584737-dc8efeb9-71ec-4427-b421-fda714ba9034.png">

Need to research. Wonder if it's a race condition where our glossary gets back to us _after_ the search does or something, and never prepends.
