### ISSUE TITLE
whitespace issue: inline code is rendering gaps (`  `) as aces (` `)

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#1332]
E.g. `:-  1  2` is rendering as `:- 1 2`, see near the bottom of https://urbit.org/docs/hoon/hoon-school/hoon-syntax for an example, but it seems to be happening all over the site.

Not sure when this happened. I tried looking at vercel deployments on PR's from 6+ months ago and it was still rendering that way, and I know it hasn't been broken for that long, but I also don't know the details behind how those are generated.

**Comment by drbeefsupreme** [comment]
Lol, its happening on Github too it looks like. That's supposed to be a double space and a single space in the title, and `:- (two spaces) 1 (two spaces) 2` vs `:- (one space) 1 (one space) 2`. I'm guessing this is related to a markdown parser dependency then?

**Comment by drbeefsupreme** [comment]
I'm seeing this behavior in Chrome, Brave, and Firefox (all the browsers I have installed) running on NixOS.

**Comment by Fang-** [comment]
Note also the different behavior between:

```
big  one
```

`smol  one`

Both of which I put two spaces between, but only the big one (triple-backtics) shows the double spaces.

The former gets rendered as a `<pre><code>` block, whereas the latter is just a `<code>` block. This is true for both Github and our site, so could be a markdown spec thing?

We'll probably want to update our rendering to just always use `<pre>`. It's the only(?) html element that explicitly preserves & renders all whitespace within it, whereas contents of `<code>` (and other elements) just collapse down into single spaces.

**Comment by tinnus-napbus** [comment]
I think you can change the css to `white-space: pre-wrap` to not collapse whitespace without having to change to `pre` tags. Not sure if the markdown parser itself also collapses them though
