### ISSUE TITLE
HTML gets double-parsed

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit.org#1358]
either just HTML or all markdown in general seems to get double-parsed. 

For example, in [this doc](https://raw.githubusercontent.com/urbit/urbit.org/master/content/docs/hoon/guides/sail.md) I had to convert HTML entities into HTML entities, so `&lt;` is `&#x26;&#x6C;&#x74;&#x3B;`, in order for it to render correctly. Additionally, HTML gets parsed as HTML even when it's in fenced codeblocks.

**Comment by tinnus-napbus** [comment]
ok in preformatted codeblocks it only happens when the language is specified as html, so there's something going on with the syntax highlighter maybe

**Comment by matildepark** [comment]
@tinnus-napbus Curious why you wrote this section in straight DOM; you can [write a table](https://github.github.com/gfm/#tables-extension-) in Github Flavoured Markdown and it should avoid this?

**Comment by tinnus-napbus** [comment]
you cannot include multiple lines in a single cell in a markdown table unless you do \<br>...\<br>...\<br>... which is impractical if it's large.

This problem also occurs in fenced codeblocks with an html language specification. In my example above I have to double entity encode the contents of the html table but even if it were a fenced codeblock I'd still have to entity encode html

**Comment by tinnus-napbus** [comment]
also \<br> \<br> \<br> wouldn't work for a fenced codeblock I don't think

**Comment by matildepark** [comment]
I think we're literally using two different parsers in our build for some reason. Need to play around with markdown pipeline here. Can you give me original input for those HTML entities to try out?

**Comment by matildepark** [comment]
As per #1540 note that Markdoc has its own table spec on top of GitHub tables that was written specifically for rich content like code samples — see [here](https://markdoc.io/docs/tags#table). I [hand-ported all our tables](https://github.com/urbit/urbit.org/pull/1540/commits/a7a9ce04c98b2eae523db1daf29be863e75ef0b8) and it looks fine on that branch.
