### ISSUE TITLE
Search function points to 404 pages, and is generally almost impossible to use to find anything other than rune references

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit.org#1394]
Please revamp this entirely. It's impossible to find grant invoicing pages, it's impossible to find software distribution pages, etc etc etc

**Comment by matildepark** [comment]
Need some replication cases to make this actionable; a de-fuzzed implementation in #1411 but what's the 404 pages you speak of? What pages are unindexed? We pull the index on build, it could be missing a directory (though hopefully not).

**Comment by matildepark** [comment]
Gonna close this because I de-fuzz'd the search; added debouncing and fixed some of the rendering issues. It should be a sane search — at worst, the same as urbit.org (2019). Re-open if you find something new ...

**Comment by ynx0** [comment]
Okay, so I have a simple example: if you're trying to search for `+got:by` using the string "got" does not suffice. "Fine, a bit too general", you say, and next you try "got by", thinking, of course that would work. Not so, unfortunately.

**Comment by matildepark** [comment]
Sure, I can make glossary search work like normal search (right now it's exact matches only).

**Comment by ynx0** [comment]
@matildepark another datapoint for improving search ordering: try searching for the `+cat` function.. instead of bringing up `+cat` as the first element, it instead brings up `bif:by` because it has the word bifur*cat*e in it.
