### ISSUE TITLE
Stream uses old talk main.js

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit.org#14]
It seems stream is still using a version of the talk/main.js that doesn't incorporate urbit/arvo#420, causing it to fail to load messages when an `%app` message is among the most recent messages.

**Comment by xykj61** [comment]
Good catch; this explains why I couldn't load a Stream feed last night. But, how does that make sense if the path is the same for normal web talk?

```
...
<script src="/=home=/web/talk/main.js" />
<link href="/=home=/web/talk/main.css" rel="stylesheet" />
<talk chrono="reverse" station="home" audience-lock default-glyph="=">
  <load />
</talk>
...
```

**Comment by xykj61** [comment]
Is this a %ford caching issue? Doesn't seem like it would be after enough time. `/=home=/web/talk/main.js` should be the most current `:talk` `main.js` it seems.

**Comment by Fang-** [comment]
Doesn't the web ship run its own slightly modified version of arvo? I wouldn't at all be surprised if it just needs manual updating.

**Comment by xykj61** [comment]
Ah, you're right. CC @ohAitch, but I can do this myself now too.
