### ISSUE TITLE
/keys can produce a %remove-graph, which is reasonable.

### ISSUE THREAD

**Issue by rabsef-bicrym** [urbit/urbit.org#1431]
[/keys sometimes produces a %remove-graph](https://github.com/urbit/urbit.org/blob/7b452a68da38a537486932588267490ea35dbf76/content/docs/userspace/graph-store/graph-store-reference.md?plain=1#L59-L64) and yet it does not so mention in the documentation.

Line 178 of graph-store produces a %remove-graph on /keys.

**Comment by rabsef-bicrym** [comment]
incidentally, this is obfuscated by the use of `+give` which took me a second. maybe a little primer @ the top of the graph-store file about `give` being used like this would be prudent.

**Comment by matildepark** [comment]
Graph Store is no longer documented on our sites. See %docs for it.
