### ISSUE TITLE
invalid RSS dates for events

### ISSUE THREAD

**Issue by mndrix** [urbit/urbit.org#1492]
The RSS feed for urbit.org at https://urbit.org/rss.xml has many publication dates in an invalid format.  Specifically, the dates are given as the exact text `Invalid Date`:

```xml
<pubDate>Invalid Date</pubDate>
```

The problem seems to be exclusive to URLs beneath `https://urbit.org/events/`. For example, this recent sample:

```xml
<item>
      <title><![CDATA[Urbit No-Coast Weekend Meetup]]></title>
      <link>https://urbit.org/events/2022-05-06-urbit-weekend-kansas</link>
      <guid>https://urbit.org/events/2022-05-06-urbit-weekend-kansas</guid>
      <pubDate>Invalid Date</pubDate>
      <content:encoded><![CDATA[...]]></content:encoded>
</item>
```

**Comment by matildepark** [comment]
Good catch. Events use a weird date format to configure it for various timezones. rss.js should just special case it and rewrite the date.
