### ISSUE TITLE
improper rendering of text in `<...>` enclosure

### ISSUE THREAD

**Issue by sidnym-ladrut** [urbit/urbit.org#1515]
See the latest rendering of [the basic moon documentation](https://urbit.org/using/os/basics#moons), which has the following source:

> Note the `<moon-name>` excludes the leading `~`. The `-c <piername>` argument is not required, but it is recommended; otherwise, the resulting directory is a rather unwieldy moon name. Moons are automatically synced to their parent `%kids` desk, and can control applications on their parent planet using `|link`.

And the following rendering:

![urbit-org-lt-gt-code](https://user-images.githubusercontent.com/95509207/168954122-c84da1df-f139-49ff-9e69-73ccf3ca12f6.png)

**Comment by matildepark** [comment]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/20846414/172878611-5c3987c3-82b2-4dde-9d1c-a9133b04440b.png">

Fixed in #1540
