### ISSUE TITLE
search: implement smarter algorithm

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit.org#1528]
In particular we should sort incoming queries by [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance).

**Comment by ynx0** [comment]
@matildepark idk if here or the old bug is the best place to put this, but anywho I found another issue and good test case for improving search. 

If I want to find the docs for software distribution, https://urbit.org/docs/userspace/dist/dist (or even https://urbit.org/docs/userspace/dist/dist for cli help), I cannot do so with the query "software distribution", nor even "distribution".

**Comment by matildepark** [comment]
We index the slug and the title and do a partial string match on both. Because "distribution" or "software distribution" isn't in the title nor the slug for both, they don't show up. I think the OP here might solve that? Depends how fuzzy the result would be. But I don't know how to surface software distribution when it isn't in any of the metadata. Possibly we could introduce page tags?

**Comment by ynx0** [comment]
Yeah or I guess just name pages better :sweat_smile:
