### ISSUE TITLE
Section anchors are still not properly generated in the glossary

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit.org#1562]
For instance, jumping to the entry for `|~` *barsig* takes you to `hoon/reference/rune/bar#-barsig`, but the actual url (slug?) is `hoon/reference/rune/bar#|~-"barsig"`.

It should be noted that the anchors *are* properly generated in the sidebar.

**Comment by matildepark** [comment]
See #1559, we're on it.

**Comment by ynx0** [comment]
wow you guys are fast

**Comment by matildepark** [comment]
As of the above commit the glossary searches should work, they resemble the URLs on my cursory glance through rune pages.
