### ISSUE TITLE
Fix hyperlinking when assigning multiple contributors to a single grant

### ISSUE THREAD

**Issue by thelifeandtimes** [urbit/urbit.org#1578]
If multiple `@p`s are listed in the `assignee` metadata field for grant .md files, neither will build into hyperlinks to their respective public links pages. See the history of this PR: https://github.com/urbit/urbit.org/pull/1571

**Comment by matildepark** [comment]
I already did this on the `multiple-grantees` branch when Mike asked earlier in the day. I said he should base his work off it for the pr that required it.

**Comment by thelifeandtimes** [comment]
is there a way that I can view a deployment for a branch w/o a PR?

**Comment by matildepark** [comment]
Yes. Every commit has one. Click the checkmark and then click 'details' and you can click through to the deployment URL from that page.

<img width="929" alt="image" src="https://user-images.githubusercontent.com/20846414/174411561-e53b65e3-9319-48d3-8828-b25d5234f8f9.png">

**Comment by thelifeandtimes** [comment]
The `multiple-grantees` branch is behind the commit that actually adds multiple grantees; do you want me to PR the recent master changes into that branch (I don't know exactly how but now seems as good a time to learn as any I suppose)?

**Comment by matildepark** [comment]
```
git checkout master
git pull
git checkout multiple-grantees
git merge master
```

The branch has a breaking change: all grantees must be in array format (`[“one”,”two”]`). All posts are updated on that branch to fit. What you merge in also will need to match that.
