### ISSUE TITLE
Dark mode detection and/or toggle

### ISSUE THREAD

**Issue by nick1udwig** [urbit/urbit.org#1588]
As a dark-mode-using-urbit-dev, urbit.org/docs is the main site I flashbang myself with frequently. Please add either automatic dark mode detection or a toggle to enable/disable dark mode.

**Comment by gordoncc** [comment]
This is a great idea and one we're going to prioritize

**Comment by gordoncc** [comment]
Automatic dark mode detection officially enabled.  Happy hooning
