### ISSUE TITLE
Application page could use some more spacing

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit.org#1631]
![image](https://user-images.githubusercontent.com/9275716/178280127-6164cac4-deca-4679-9fb0-0bda7ac62c53.png)

Best explained with a picture here.

Basically the button seems too close to the Website/Developer section, which also feel scrunched up next to each other a bit.

This is also just a minor nit/observation but the header typography seems just slightly weaker than the URL typography (size and color).

**Comment by gordoncc** [comment]
Thanks for bringing this to our attention – things are a little more balance on spacing now
