### ISSUE TITLE
Broken link on "Moon" glossary page

### ISSUE THREAD

**Issue by mcevoypeter** [urbit/urbit.org#1657]
The [`"Using Your Ship`](https://operators.urbit.org/manual/os/getting-started#moons) link on the [moon glossary page](https://developers.urbit.org/reference/glossary/moon) is broken, yielding 404 "Not found" when clicking through.

**Comment by matildepark** [comment]
Fixed by https://github.com/urbit/developers.urbit.org/commit/e6a3b97bc3d93ea970bd004f677a93916b77aa44
