### ISSUE TITLE
Exponents not rendering properly

### ISSUE THREAD

**Issue by gordoncc** [urbit/urbit.org#1686]
Found a typo on the urbit intro page:
Urbit IDs are distributed by a sponsorship tree. At the top of the tree are 28 (256) galaxies. Each galaxy issues 28 stars, making a total of 216 (65K). Stars then each can issue 216 planets, making for 232 (~4B). As you might expect, each planet issues 232 moons.
https://urbit.org/overview/urbit-id

**Comment by matildepark** [comment]
Already aware; our custom patched markdoc isn’t patching after install (so this is post #1621 regression and why I wrote iframe components in #1642). This is why I’m doing the work to deploy a versioned FDS on npm right now - we either need to renovate build process again to figure out where to slot in patch-package or we basically need to deploy a fork of markdoc instead. The latter is easier to do and to maintain in future. Then we deploy FDS on npm alongside some semantic versioning process to prevent future build issues with vercel deploys.

**Comment by matildepark** [comment]
(And yes, Markdoc doesn’t support superscript even. This is weird to me, but the things we patch into markdoc I imagine will be supported in future enough that we won’t need our own deploy).
