### ISSUE TITLE
Linux binary retrieval instructions don't work

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#171]
The Linux instructions for `curl`ing the binary end up with an unresolved host:

```
$ curl -O https://bootstrap.urbit.org/urbit-linux64-v0.8.2.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: bootstrap.urbit.org
```

It works fine for macOS!

**Comment by matildepark** [comment]
It works for me, both in browser and curling it.

I find the bootstrap link sometimes gives that error, depending on my own connection. What happens if you retry it?

**Comment by belisarius222** [comment]
Have you checked that your linux machine can curl other domains?

—
~rovnys-ricfer
https://urbit.org

**Comment by matildepark** [comment]
I still can't replicate this and this has been open for a few months without any indication it's an issue for others, so, closing.
