### ISSUE TITLE
Application images don't appear in opengraph previews

### ISSUE THREAD

**Issue by gordoncc** [urbit/urbit.org#1757]
Example tweet: https://twitter.com/darkvesak/status/1561887249154813952

![apptweet](https://user-images.githubusercontent.com/364577/186277449-ab8e4de5-e443-42db-b492-afc59d162363.jpg)

**Comment by matildepark** [comment]
Counter-point:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/20846414/186278277-77f8a064-416a-4bd6-a682-99ac53515db1.png">

Chess uses a .svg tile image. Twitter does not:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/20846414/186278418-597ea36e-8e61-491f-83a5-b57ce05f5de7.png">
