### ISSUE TITLE
The safe wallets that may belong to Urbit ID: Deployer were identified as airdrop farmers' wallets

### ISSUE THREAD

**Issue by xiaohu1882** [urbit/urbit.org#1805]
Hi, I noticed that many Gnosis safe wallets closely related to official urbit id deployer(https://urbit.org/overview/urbit-id) were identified as airdrop farmer's wallets in https://github.com/safe-global/safe-user-allocation-reports/issues/124. Hope the team can look into it.

0x00b2e3c4347e314a931bfff899d239222ec8cc9f
0xfb6df432f02d4099e0c176902351d8e79120af7d
0x02c1be7ce8c07096308db18b82fe446c12dcac5d
0x067a373420e67e4c0edbb547ed6133b83eb8c7a4
0x09239e16302cc0a6676ba0928ac44ff922a31992
0x09a8ee7b662cc0c8d1effaf6c9fc526383f5bca1
0x0a194d74ee18ffe5b464e74f2ff745bf9b7790fc
0x0c6df9ca3805b95094596cd6fb24d335b7adca0e
0x0ca7f4fa293118f7f31cd8154d5242323c9e572e
0x0cdb9333efe7e358f1bdfaf9980a41846688db8c
0x13dadbed45d857cffdaa0e14769ac258fb672250
0x149b0c5e1e91911c141c24db4386589b4e08ba09
0x157c68b10a3f9311ac6d01862b69203ffe5e08d8
0x16dd55be903e0ed4c6fbdba703c3c223b76cc8cd
0x17dcf09ae8525d49ad92a319e603ce564c4ca002
0x1bac1284c4de3dd00304369134fff4f5abeaaf5a
0x1ddef81e9d3a5aa4d30ff740b5c9bfa66a176969
0x20f7bc4d4c65d4c3fa2f72b4820c72c3190ac4e8
0x2bfa25f946fbef42333098e8898171817d1c3348
0x2d83946b530b99e823e9c9896e0e0f05bd5d1fce
0x307191f294323f6d84168ca88d9c8e69ead638f6
0x30c011f8b14add6c009b210aad2e084cd152f2d7
0x31422acef5b42363f0e3b2f9090a21367b7663db
0x3e26190daacc364eca378e4591bca6eb6c05078d
0x3e7bd7229665d19fe319b76605edc0b437655d7b
0x4aa9ce2404aab305a0cae4ebfb7445894a2f2939
0x4c54158862efca245de42af011b3306afeb9c6bb
0x4cdcbaed9be1be2e59e349e615b4a7dafb934a28
0x52d48f2a8b8b23533a6d407d38b8a19b12ca6df3
0x53754c51bd2ddccdbb85c8e63827011d2fed646b
0x53e8272301d4db1a57d3604f8b0cb1503d4cefa1
0x57a50a09bd0378b0154f27d9d0ac87ae9e8c9ecc
0x598874bfb8865f6d37bbdf56346dad780973cd6d
0x6229842f1c8243ecf90dc271ec8d069e65b43e8a
0x68b9afc779d86099fd378fc31c037e19c6cc8440
0x6b925675a51c9ff22afae5f3c2e0bbdc9d16097c
0x6d152c1191ef723876ff5fcee6c9b6acb861a73b
0x6ebcf2f709693968710e441c9f70573dba718627
0x6f9a33c8aa249bfe63b285f3815d08410675513c
0x71d18fd8f78c4afda917a6297f611f012b05d1c6
0x7a0c7b161f706f3d0b806e33606f623e14f94197
0x7dd06d8144238e53f01d2268b6760ec252b83520
0x8099b697663447ed94ec028e005327765a44ba70
0x82ca887f3ce5f07dddb3f05c67b881dea9de7da9
0x860d04e3cf4856f1697e09a9b64fab4b4dfc5d0b
0x89e1d7759ff1c8f0283df0c17f0618caf7b694f2
0x8a2d1c9c8946b8efebd1994688eddd3f9822c747
0x8ba8a3e0ac02fe8f91f30afcd9f19720b5ad04a4
0x8f24659356998ba459fea898f738362237eed53c
0x8fd100c68015993468bd41c7410e46044111131f
0x8ff7bf90a90e5da515b4e9ea086016af7e8465c1
0x976c3d006b1e3cd7ef1a4fbca9aa34b25ff07f2e
0x9ca43d919569d1e86799220fa9afab71423b1697
0xa029107e4e564fcd858489874e122117ce40c135
0xa3c1bd39ba24420cd04d6f97b78b911698a5a67d
0xa58bf3fe3caedaa9738fac00857dfd9150969075
0xa6e9822bd49dd0faec0664870beea8d48a122051
0xaafbf2b1040db63d8e85197303c3dc73977e2efd
0xab6ac840a1852046c8953333fc4f869cbb64b794
0xac4d0d17aead3ae5555d6bf5b22f5f9470e67fce
0xaef10838d3b01355e2531d992f700cfb8467ea96
0xaf1f5c6f8d8065ecd8106212b0241cc2345cd7db
0xafa96b1af942cd9ae789c5e4d86e4c7174503efa
0xb17c5cd5671233bc1697b50e8298d401110b90bb
0xb26ad38491a45c44b69b1322155b5dfbffc98cb0
0xb4e5db6ae290a8990b1316145e84db9f55993748
0xb5824001cef4324cb211606bb10dd69a6fc3591e
0xbe2aec3d9f951767034e8bce739b227f4878c3c4
0xc135363f9b418740cdfd10c8b38c7ac91f215d17
0xc1f19a941bbaa3aa7b70e13eed958b6744c3baf6
0xc1fb49056ae14bfd814630a21cc1e902d229797b
0xc9b90bcf2c45b48defcadecd638c356ae949717f
0xd15c6c2848c4e132c925d55f3d6bf41799ddbe54
0xd32469f7afefe0c9e9592b460e5d310980144be7
0xdb37c2d3825b79203bbaa71166ffdea25347b673
0xece1ed6fa335350a242addc97493b781ce17f960
0xf29c1553a5d815148ea6b6dfe29abfe181c019b6
0xf2dc50beb378f48146401603b6b770deb359f6ed
0xf37e79d7e1bb76875d288d2719afafa640479812
0xf9092d4ae81464c0a0430acbe1d570d04ac799ac

**Comment by matildepark** [comment]
I'm honestly not sure what to make of this issue or where even to redirect it.

**Comment by xiaohu1882** [comment]
Closed
