### ISSUE TITLE
Search by grant directs to an invalid url

### ISSUE THREAD

**Issue by thelifeandtimes** [urbit/urbit.org#1857]
@matildepark the recent directory sorting to categorize grants by year while not changing the URL gets us an issue whereby if you `ctrl + K` search for a grant and follow that link, it will go to an invalid url that 404s. Looks like it is because it finds the `/2022` directory and attempts to put it in the URL.

**Comment by matildepark** [comment]
Ah it just needs a catch for grants like the others do
