### ISSUE TITLE
Grants page renovation

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit.org#1874]
- [ ] Show link to associated applications in completed grant page

- [ ] Show link to proposal group in applications
https://www.figma.com/file/rlQkryJk1WjzTnMNZzsAkl/Urbit.org?node-id=427%3A1145

- [ ] Button on grants page to go to either Urbit Group or Public Link page for Group

**Comment by matildepark** [comment]
About halfway done here — we presently use `link` in the `extra` section of grants files for nothing; not even one has an entry in there, so it isn't clear what it's for.

@thelifeandtimes do you want me to use this `link` metadata entry for the deliverable, or is it for the group? Should I add another `deliverable = ""` section?

@gordoncc How would you like linking to the group to look? I can riff but curious since it is unmocked.

**Comment by thelifeandtimes** [comment]
As far as I'm concerned, `link` seems like it would make the most sense for the on network group, i.e. `web+urbitgraph://group/~sampel-palnet/rando-group`, while adding a `deliverable` section makes sense for pulling in a card for an ecosystem page public link listing. Linking to the on-network groups I think should look in line with what we have on the ecosystem groups pages.

**Comment by gordoncc** [comment]
@matildepark Let's slot it in the metadata the same way we do the link to the deliverable.

<img width="1060" alt="Screen Shot 2022-11-01 at 10 11 57 AM" src="https://user-images.githubusercontent.com/364577/199294693-f45a772c-739b-447e-8451-b638ce48744f.png">

**Comment by matildepark** [comment]
So same sort of card if the public link page exists? Or never link to a public link page, always a group?

**Comment by gordoncc** [comment]
Oh that'd be nice to use a card if the public link page exists, let's do it that way.

**Comment by thelifeandtimes** [comment]
Public link pages will rarely, but perhaps occasionally, exist for proposal groups (because if we require them for every proposal group, that page on the site will just be drowning in half dead proposal group links).

**Comment by matildepark** [comment]
That's what I thought. It might be better to just show the group link and leave it there.

**Comment by gordoncc** [comment]
I suppose that makes more sense.  Either way works for me.
