### ISSUE TITLE
Getting Started / Joining Groups instructions are out of date

### ISSUE THREAD

**Issue by thelifeandtimes** [urbit/urbit.org#1927]
@gordoncc, the screengrabs and some of the instructions at https://urbit.org/getting-started/joining-groups are out of date given Tlon's release of new Groups. Would be good to get new screengrabs and some updates to explain the new methods for searching for groups.

**Comment by gordoncc** [comment]
Addressed in https://github.com/urbit/urbit.org/pull/1928
