### ISSUE TITLE
Getting started curl links don't work

### ISSUE THREAD

**Issue by zalberico** [urbit/urbit.org#1959]
The getting started links for the linux binaries don't work.

See: https://urbit.org/getting-started/cli

I tried curl -L https://urbit.org/install/linux-aarch64/latest | tar xzk --strip=1 && ./urbit and it both the download and ./urbit fail.

We shouldn't have merged this without testing.

Related: https://github.com/urbit/urbit.org/pull/1943

**Comment by zalberico** [comment]
Tagging @matthew-levan @jalehman and @mcevoypeter for context - we'll go over this tomorrow at the release sync.

**Comment by matthew-levan** [comment]
> Tagging @matthew-levan @jalehman and @mcevoypeter for context - we'll go over this tomorrow at the release sync.

Just needs to be `curl -L https://urbit.org/install/linux-aarch64/latest | tar xzk && ./urbit`. The binary name needs to be changed too because right now it'll extract as `vere-v1.16-linux-aarch64`. Sorry to see this go out broken, it was my mistake.

**Comment by jalehman** [comment]
> Sorry to see this go out broken, it was my mistake.

And I should have verified everything worked before/after pressing the merge button. Whoops.

**Comment by zalberico** [comment]
Thanks guys - we'll get it fixed. And yeah, always good to verify post merge that things look good.
