### ISSUE TITLE
For docked binaries setcap needs to be run on .run not ./urbit

### ISSUE THREAD

**Issue by zalberico** [urbit/urbit.org#1970]
Reported by @rabsef-bicrym - if you have docked your binaries following the instructions in the getting started guide and you're on linux, the setcap command should be run against <pier>/.run not ./urbit

**Comment by rabsef-bicrym** [comment]
Further investigation reveals that I needed to do `sudo setcap 'cap_net_bind_service=+ep' ./my-pier/.run` for it to work the way I normally run it - IDK if that's just me being bad at sysadmin or what.

**Comment by zalberico** [comment]
No I think that's correct - I'm creating a PR to update the docs now.

**Comment by zalberico** [comment]
I also have to update the earlier parts of the dock to - they should all be pointed at .run.
