### ISSUE TITLE
ecosystem: groups application has references the wrong distribution source

### ISSUE THREAD

**Issue by jalehman** [urbit/urbit.org#1995]
The [Groups ecosystem page](https://urbit.org/applications/~marnec-dozzod-marzod/groups) indicates that it's distributed from `~marnec-dozzod-marzod`. This is the release candidate moon, which should only be synced from by more dedicated users that want to test prerelease software.

**Comment by gordoncc** [comment]
Addressed in https://github.com/urbit/urbit.org/pull/1986
