### ISSUE TITLE
Can't link to sections of Getting Started

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit.org#2004]
I'd really like to link people to the `Docking` section of the getting started guide, since a lot of people have been asking me about it.  Instead, I have to tell them to go to the page and then look at section five.

**Comment by gordoncc** [comment]
You can link to any heading in all the markdown pages of urbit.org with a slugified anchor tag.

E.g. section 5: https://urbit.org/getting-started/cli#5-runtime-upgrades
