### ISSUE TITLE
/docs landing links resolve to 404 (firefox)

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#223]
The three highlighted links in the /docs root resolve to 404 pages — I'm unsure if these pages actually exist.

<img width="1472" alt="Screen Shot 2019-10-15 at 11 42 39 AM" src="https://user-images.githubusercontent.com/1195363/66859945-14a85680-ef41-11e9-9194-61323e754f32.png">

**Comment by matildepark** [comment]
This is for the docs repo. I'll amend the links.
