### ISSUE TITLE
Latest runtime download links missing

### ISSUE THREAD

**Issue by latter-bolden** [urbit/urbit.org#2252]
Congrats on the new site! 

Noticed the paths that used to host the latest runtime seem to have been removed. Notably, these are what gets linked to in the [command line install instructions](https://docs.urbit.org/manual/getting-started/self-hosted/cli) on the docs site. 

Example: https://urbit.org/install/linux-x86_64/latest

This would also be an issue if you, say, happened to rely on them being there as [part of the scaffolding](https://github.com/tloncorp/landscape-apps/blob/develop/apps/tlon-web/rube/index.ts#L91) for your end to end tests  :~)

Are these accessible somewhere else on urbit.org? If not, is there a recommended alternative for statically linking to the latest release on a per-platform/architecture basis?

**Comment by pkova** [comment]
Can't win them all.

Fixed with #2253.
