### ISSUE TITLE
Difficult to go between the Technical Writing and the User Manual

### ISSUE THREAD

**Issue by baudtack** [urbit/urbit.org#228]
When I'm inside of the "documentation" section (which should have a name change because Documentation is too general and fits the things outside of that category also) it's difficult to see how to get to the user manual pages i.e. /using  without going back to the main urbit.org page. You can navigate there by clicking on documentation in the menu bar which has a link to the user manual pages but it's non obvious how to get there.

**Comment by matildepark** [comment]
Fixed in #317.
