### ISSUE TITLE
Search produces results in blog posts

### ISSUE THREAD

**Issue by baudtack** [urbit/urbit.org#229]
Searching for "dns proxy" results in two blog post pages before the docs page I care about shows up. Either search should exclude the blog posts or they should show up in some other section.

**Comment by matildepark** [comment]
Side-wide search is actually *meant* to include all site posts. If a specific term should come *first* it should be in the glossary, which is part of search. So far we only have [runes](https://github.com/urbit/urbit.org/blob/master/static/runes.js).

**Comment by baudtack** [comment]
I mean... that's fine, but they should probably have their own result area since 99% of the time when you are looking for something you're probably not gonna care about the blog posts. at least _I_ don't which means no one could possibly care. :-p

**Comment by matildepark** [comment]
They do. They come *before* the other results, and are delineated inside their own section.

**Comment by baudtack** [comment]
![Screenshot from 2019-10-16 11-39-41](https://user-images.githubusercontent.com/32079/66948548-c8751900-f009-11e9-880e-f09da74ac278.png)
Not when I've run it?

**Comment by matildepark** [comment]
Yeah. Because there isn't a glossary to stick in there yet. Just the runes.

That's my thing: If you want a definition to come *first* then you'll need to make a glossary out of JSON. I've proposed this for Docs workflow, and there's work on it that can be later deployed for programmatic export.

**Comment by baudtack** [comment]
I'm not looking for the definition of DNS Proxy here. I'm looking for the page that _tells_ me how to do the dns proxy stuff. Which is on the 3rd link there instead of the first one.

**Comment by tinnus-napbus** [comment]
seach has been overhauled, should now produce better results
