### ISSUE TITLE
Link to Github files of pages

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit.org#230]
This is more for the docs pages, but who knows, maybe we want to apply this more broadly.

Whenever I spot a small error on a docs page I want to correct, I have to go _all the way_ over to the Github repository, then _find the file_ I need to be editing. In the interest of streamlining the contribution pipeline, we should consider adding a ✏️  or similar to the docs pages, that links to the file on Github (or its edit page). Nothing too intrusive, just a little nudge.

**Comment by matildepark** [comment]
We could do this pretty easily — `page.relative_path` shows, for example, `understanding-urbit/simple-durable-yours.md`. So then you append it to `https://github.com/urbit/urbit.org/blob/master/content` or the equivalent for docs in the template. I'm unsure it's something ideal for the *whole site* though — do we want urbit.org to seem like a wiki?

**Comment by Fang-** [comment]
> do we want urbit.org to seem like a wiki?

Seems _kind of_ in line with the "Headless Brands" thread, but not my call to make. Certainly a better fit for docs than essays.

**Comment by matildepark** [comment]
Fixed by #1446
