### ISSUE TITLE
Video doesn't autoplay and button covered iOS 13 Safari

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#231]
![65F9CE48-58CF-44BD-B6F7-EA0BD10512E2](https://user-images.githubusercontent.com/31774/66889749-71832b80-ef98-11e9-8bc3-2f91280bcfea.png)

**Comment by matildepark** [comment]
It’s not supposed to play on iOS Safari. The button shouldn’t even be there (and isn’t on my iOS Safari...).

I think the button is showing because you’re in low power mode.

**Comment by flowerornament** [comment]
@matildepark you're right – and looks like it's not easy to fix. Requires a video overlay / swapping in a GIF for this specific case on iOS 12/13.

**Comment by tinnus-napbus** [comment]
urbit.org no longer has water animation
