### ISSUE TITLE
Search magnifying glass is chopped

### ISSUE THREAD

**Issue by mattlevan** [urbit/urbit.org#232]
![image](https://user-images.githubusercontent.com/4582375/66938921-e5542100-eff6-11e9-8e42-4195c1431911.png)

**Comment by matildepark** [comment]
Can't replicate on any browser on macOS. You are using ... Windows? Linux? Let me know so I can try and replicate and fix.

**Comment by mattlevan** [comment]
Windows at the moment! Browser was latest Chrome.

**Comment by rjallanreal** [comment]
nice
