### ISSUE TITLE
Side-margins eat up site (mobile firefox)

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit.org#233]
Eats up both images and overflowing text.

![image](https://user-images.githubusercontent.com/3829764/66945136-d26d3b00-f04e-11e9-9ec8-c22ed7c1f09c.png)

![image](https://user-images.githubusercontent.com/3829764/66945107-c41f1f00-f04e-11e9-8cbe-3f35cf40562e.png)

![image](https://user-images.githubusercontent.com/3829764/66945159-dbf6a300-f04e-11e9-9af2-2a310710eae9.png)

**Comment by matildepark** [comment]
I also think this one might be resolved, @Fang-, but need confirmation.

**Comment by Fang-** [comment]
Confirmed for looking slick.
