### ISSUE TITLE
The website looks weird (apple watch)

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/urbit.org#234]
I'm using Opera Desktop emulated in Android Studio which I'm running on Wine on my jailbroken Apple Watch.

![75635515-glitch-psychedelic-background-old-tv-screen-error-digital-pixel-noise-abstract-design-photo-glitch-b](https://user-images.githubusercontent.com/5265021/66945507-03744e00-f004-11e9-99ad-19a4dce979bb.jpg)

**Comment by matildepark** [comment]
Hmm. I'll try and replicate. Thanks for the heads up!

**Comment by philipcmonk** [comment]
It looks to me like a bad cable.  Have you tried jiggling the virtual HDMI cable between the watch and Wine?

**Comment by galenwp** [comment]
Legendary

**Comment by urcades** [comment]
lgtm

**Comment by g-a-v-i-n** [comment]
Ok, I ran `$ jiggle` on the VHDMI. Now it looks like this:

<img width="1359" alt="Screen Shot 2019-10-16 at 12 03 41 PM" src="https://user-images.githubusercontent.com/5265021/66950381-19d2d780-f00d-11e9-86cd-faa77d5936d2.png">
