### ISSUE TITLE
Mobile dropdown navigation allows selecting non-pages

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit.org#235]
While I agree it's nice to have section headers even in the dropdown, it's confusing that they're clickable. They get selected, but nothing actually happens, leading to the impression that navigation's broken. Pretty sure it's possible to disable dropdown options separately.

![image](https://user-images.githubusercontent.com/3829764/66945348-309a1e00-f04f-11e9-83be-d14bbb16e310.png)

![image](https://user-images.githubusercontent.com/3829764/66945136-d26d3b00-f04e-11e9-9ec8-c22ed7c1f09c.png)

(Mobile Firefox, fwiw.)

**Comment by matildepark** [comment]
You can with `<optgroup>`, but it's intended for multiple-selection situations. Just tried an implementation that worked on my desktop Brave but didn't actually work as navigation on iOS ... it also forced into multiple selection. Something to look into.

**Comment by tinnus-napbus** [comment]
the new framework doesn't have this issue (afaics on mobile firefox)
