### ISSUE TITLE
Weird scroll behavior on some pages on mobile

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit.org#237]
The content is within two scrollable containers. Can reproduce this on most pages with images, including blog pages.

![weird-scroll](https://user-images.githubusercontent.com/3829764/66946554-7a840380-f051-11e9-9bde-a41446381668.gif)

Mobile Firefox, as always.

**Comment by matildepark** [comment]
Is this still the case @Fang-? I think I fixed this in #302.

**Comment by Fang-** [comment]
Can confirm this looks clean. (:
