### ISSUE TITLE
Urbit ID graphics disagree

### ISSUE THREAD

**Issue by davis68** [urbit/urbit.org#238]
The Urbit ID graphics on the new page

https://urbit.org/understanding-urbit/urbit-id/

disagree on enumeration.

The one following "Your Urbit ID and passkey" has one set of values for number of stars and planets, while the one following "First, there are only" has another.

I'd PR but you have the image sources.

**Comment by galenwp** [comment]
Nice catch. The second image is correct. Each tier is less the tier above. That is, there are actually 2^16 - 2^8 stars and 2^32 - 2^16 planets.

**Comment by g-a-v-i-n** [comment]
Should be updated when the GCP cache expires.
