### ISSUE TITLE
Discord linked on the website

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit.org#244]
I thought this was only a temporary solution for hosting Hoon School? And that next Hoon School was going to be on Urbit proper?

It's _very_ off-brand to me to see Discord linked on the homepage.

Who is even maintaining support/structure there? What do we want it to be used for? Why is that not happening _on Urbit_?

"But ship boot troubleshooting!" Getting the binary and booting a comet is pretty easy these days. If we want to cover those cases also, maybe we should bring stream back instead? That way we don't have to support people in more different (and legacy) places than necessary.

**Comment by matildepark** [comment]
FWIW, I agree with you. However, Marketing and Communications (and @galenwp and, basically everyone else?) believe we need a direct place for people to get support that isn't an email address we control, and doesn't require you to get an Urbit ship; Discord is the easiest option.

Me and another are essentially volunteering to steward over it.

**Comment by baudtack** [comment]
Given that "ship support" is basically been dumped in my lap, @matildepark 's lap and the lap of students who are very graciously volunteering time to help randoms boot ships, I could not agree more. This is awful. At the _very_ least more tlon people NEED to be in there to provide support if that is what it's for.

**Comment by ohAitch** [comment]
Does booting a comet no longer take an hour of mining? Even then, "pretty
easy" seems likely to involve the precise same pitfalls that "ship booting
troubleshooting" refers to in the first place.

**Comment by baudtack** [comment]
Also, maybe i'm a jerk but if you can't boot a comet, urbit isn't ready for you yet.

**Comment by Fang-** [comment]
@ohAitch Comet boot speed improvements are in the pipeline and will be shipping Soon™.  
Fair re troubleshooting.

> At the very least more tlon people NEED to be in there to provide support if that is what it's for.

I am more than happy to do support during all my at-keyboard hours, but feel conflicted about falling into a "20 messaging apps" situation.  
Reimplementing stream for our current stack would allow us to provide a no-account-needed instant-messaging support channel that feeds directly into Urbit itself, where people are around to help most of the time.

(I wouldn't be opposed to Doing The Work on this myself, especially given the new/more stable eyre. (And in spite of the fresh-out-the-oven new chat.))

**Comment by ohAitch** [comment]
I suppose "use API drivers to bridge chat to a channel on the official discord" would be out of question, bc travesty hell etc?

**Comment by vvisigoth** [comment]
So this issue is that we should staff the Discord with people who are willing to help. Good point. Not a website issue.
