### ISSUE TITLE
cannot search for Ford runes

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#246]
Ford runes begin with `/`, but typing `/` into the Search bar closes out of it.

**Comment by matildepark** [comment]
We can change the hotkey easily enough, but [Ford runes aren't in runes.js anyway](https://github.com/urbit/urbit.org/blob/master/static/runes.js). Needs to be added, if you want them — since they're not listed as runes on the runes pages, only on Ford's page, they weren't processed.

**Comment by drbeefsupreme** [comment]
I'll discuss what we should do about this with the docs team on Monday, since they ought to be separate from Hoon runes somehow, but they also ought to be searchable.

**Comment by matildepark** [comment]
You could just add them to runes.js without moving the docs around? The hotkey thing is my part — We just change the hotkey event listener in scripts.js.
