### ISSUE TITLE
Can we restore the gray background for inline code?

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit.org#253]
The code font and the script font look very similar and the different background would help see these better.  We used to have it, and we still do for block code.

**Comment by rmariani** [comment]
@matildepark, what do you think?

**Comment by matildepark** [comment]
This is a design question. I personally dislike gray backgrounds on them, though. @g-a-v-i-n ? I think we were thinking about a lighter gray compromise?

**Comment by g-a-v-i-n** [comment]
I think they should be reinstated. Its helpful to be able to scan for code blocks.
