### ISSUE TITLE
Broken Link on Hoon Tutorial's first page

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#260]
Url: 

https://urbit.org/docs/tutorials/hoon/setup/

Screenshot of location:

![image](https://user-images.githubusercontent.com/1195363/67743568-6cd96100-f9f5-11e9-9d72-4048fbd0d601.png)

Clicking this link resolves to a 404, at url https://urbit.org/install.md.

I can attempt to rewire this myself sometime Tues, but I need to learn how we're linking pages so I do it properly. If someone just knows how this works, please go ahead and fix.

**Comment by matildepark** [comment]
Good catch. If it's in `/docs` then it's in [urbit/docs](https://github.com/urbit/docs). 

That said, I went ahead and fixed the links on this page and pulled it into the site, so this is fixed as of b6089917191cb0f12eb8f014739ce00535ab909c.
