### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit.org#263]
Going to urbit.org/docs gives the first error below, and typing /foo gives the second error (repeated on every keystroke).  No search results appear.

```
Uncaught SyntaxError: Unexpected token '{'
scripts.js:276 Uncaught ReferenceError: runes is not defined
    at HTMLInputElement.<anonymous> (scripts.js:276)
    at scripts.js:48
```

On Chrome 78, MacOS High Sierra.

**Comment by matildepark** [comment]
Ford rune additions to JSON didn't have commas. Sorry, should've caught. Patched in 54510001eafdc390f2a2d18a98aebffdd1641a0e.

(If you look for Ford runes, it'll still close on you, since #262 still needs to be reviewed before merge.)
