### ISSUE TITLE
feature request: dynamically generated lesson, exercise, etc. numbers

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#269]
The Hoon school lessons are under constant revision, and as such, the lesson numbers frequently change and so any references to them must also be changed manually. Exercise numbers, written as "Exercise 1.7a" for the first exercise in Lesson 1.7, also depend on these lesson numbers. With the planned expansion on adding figures, additional exercises, etc., a general purpose reference system that generates lesson, exercise, figure, etc. numbers automatically according to their placement in the table of contents will cap off an unbounded source of busywork.

Besides titles for these objects, we should also be able to reference them from elsewhere in the text, like "See Figure 1.4.4" being a hyperlink to that figure.

**Comment by matildepark** [comment]
We discussed this out of bounds first.

My thought on going about this is crafting a new template page for the Hoon tutorial directory that generates the table of contents, which would then auto-sort the numbers.

As for figure linking, my initial approach — inserting the IDs on page load — doesn't help with hyperlinking. I'll think on it. This is lower on priority for me at the moment but I'll come to it.
