### ISSUE TITLE
/docs sidebar doesn't remember your place

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#28]
@belisarius222:
> When I click an item in the sidebar, it scrolls all the way back up to the top. This is pretty unpleasant.

**Comment by flowerornament** [comment]
@friederjanmoerman can you let me know how hard you think this would be?

**Comment by hardcodepunk** [comment]
At first sight an idea of mine would be with JS extract a parameter from the url to make it scroll to a location/element with a given id. This is a few hours of work.
