### ISSUE TITLE
Urbit ID page is unclear on whether Urbit OS is implemented in Solidity

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit.org#287]
![image](https://user-images.githubusercontent.com/1377557/68972239-2f6c2600-07a0-11ea-9380-dad4c630a66d.png)

https://twitter.com/GeorgeGoognin/status/1195429689785044992/photo/1

**Comment by galenwp** [comment]
Simply adding a sentence that Urbit OS is not built on ETH nor is it a hard dependency / could be moved is totally fine with me.

**Comment by tacryt-socryp** [comment]
Perhaps instead of "All of this", we just say "Urbit ID is implemented as a suite of Solidity contracts" etc

**Comment by galenwp** [comment]
Also fine

**Comment by matildepark** [comment]
As of ~2019.12:

> The Urbit ID registry is live and deployed to the Ethereum blockchain. Urbit ID isn’t specifically wedded to Ethereum – someday we’d like it to be hosted by Urbit OS itself. Also, Urbit ID is the only component of the stack using Ethereum – your Urbit OS node is hosted wherever you choose.
