### ISSUE TITLE
Ordered lists don't display correctly

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit.org#29]
The numbers appear on different lines from the content of the list-elements. Look at the "Getting Started" part of this page

https://urbit.org/docs/getting-started/

Seems to be an issue in `/static-site/css/lists.css`

**Comment by jyng** [comment]
I don't think it has to do with `lists.css`, unless you can point to a specific part of the CSS. It has to do with the way lists are outputted.

There's a `<p>` tag inside the `<li>` and the `<p>` tag is a block element so it takes up the whole row making it go onto the next row. I'd like for this be a Sail fix where <p> tags are not inserted. @vvisigoth Is this doable?

**Comment by vvisigoth** [comment]
Need to remove auto-adding a p in converting from udon->html
