### ISSUE TITLE
"Using" section too separate from docs?

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit.org#293]
(I think this goes here instead of the docs repo.)

Maybe I'm blind, but it seems like the "using" section of the docs isn't actually reachable from the sidebar as displayed on [`/docs`](https://urbit.org/docs/)? Perhaps related, the root page is at [`/using`](https://urbit.org/using/) instead of the more-expected `/docs/using`.

Did we split "using" from "docs" intentionally? The "user docs" vs "tech docs" split makes _some_ sense to me, but certainly they should still link to each other. (Especially consider the `/using` pages are linked much less prominently from the homepage than `/docs`.)

**Comment by matildepark** [comment]
Using was split out intentionally, there was a long IA discussion about it. Essentially, yes, that we needed to start separating user-facing usage information from development stuff. 

The Docs navigation used to link to the Developer’s Guide and Operations Manual as top level items! It was removed but I don’t know why. Perhaps it should be restored there. I would also consider strengthening the flow from the install to the usage instructions.

**Comment by rmariani** [comment]
Using/operations doc were split off because of our philosophy of urbit.org being for normal people to actually do something on Urbit, and docs being for developers. 

I do think the flow can be improved, and I think that the docs navigations should link to this stuff. I am going to make a few changes this week.

**Comment by matildepark** [comment]
Note that adding links to user-facing information doesn’t necessarily mean changing the Docs repo! We can just change the docs navigation template to add the Using and Operations links above the drawers.

— 
~haddef-sigwen
http://urbit.org

**Comment by thunderrabbit** [comment]
I see "Dojo is working correctly" at the bottom of https://urbit.org/using/install/ and then have to spend tens of minutes looking for how to merge a desk on a new ship.

I understand needing a distinction between users and developers..  So maybe at least could put links to the "next" things on https://urbit.org/using/  which are https://urbit.org/using/develop/  and https://urbit.org/using/operations/
