### ISSUE TITLE
Confirmation email when one signs up for Hoon School

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit.org#295]
A lot of enrollees expect this, and are confused when they receive no such email. Could we automatically send one out when someone signs up?

**Comment by matildepark** [comment]
This is probably something we can do in Airtable directly.

**Comment by matildepark** [comment]
This is apparently something we can't do in Airtable directly, thanks Airtable.

Right now the form will say "Thanks for applying to Hoon School." when it's completed. We can:

- redirect the user to a URL (we write a page to confirm and if we want a more "serious" feeling confirmation with instructions on when we'll reply)
- change the copy
- get an email to the Airtable account's email when people apply. Based on this we could probably hook up an auto-reply to these emails, but whether that'll go to the applicant or to the automated Airtable email address ... ?
