### ISSUE TITLE
Standard library is gigantic on navbar

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit.org#30]
We should find a way to make this manageable. The stdlib is is about 50 pages, making it almost a third of the navbar. That overwhelms pages that are much more important for people to be able to navigate to from anywhere. Obviously the standard library is important as a whole, but pound-for-pound, those pages are low-value and eat up a lot of real estate. 

Could we make an unprincipled exception to our nav-bar philosophy and make the stdlib directory a single entry?

**Comment by baudtack** [comment]
Is there a reason we don't want to make the top level things on the nav bar collapsible headers? My design sense is pretty terrible but that seems to be a decent solution to me.

**Comment by flowerornament** [comment]
@baudtack that's a solid option, @rmariani we'll turn our attention to this in the next couple of days

**Comment by flowerornament** [comment]
Just an update: this has been stalled for a long time, but we'll get to it eventually.

**Comment by matildepark** [comment]
Collapsable headers are in the overhaul deployed next week.
