### ISSUE TITLE
Urbit.org / Docs: Ambiguous separation of concerns

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit.org#343]
Right now the Documentation for the website lives on its own repository, [urbit/docs](https://github.com/urbit/docs). However, the Operator's Manual and Developer's Guide live on Urbit.org. Both are under the purview of the Documentation team. This is a poor separation of concerns for documentation.

Additionally, Docs changes require that I update the submodule here on urbit.org whenever it changes. We could automate this part — I just haven't had the bandwidth to confront it yet.

## Why is it this way?

There was an initiative to integrate Docs into Urbit.org as part of the October 2019 redesign. I take responsibility for aborting that effort, because

a) Docs team should not reasonably expect to do all their own work on a subdirectory on Urbit.org,
b) It merges one particular presentation (Urbit.org) with rather portable, target-agnostic content

I created a counter-proposal, [~2019.9 Systematising documentation deployment](https://docs.google.com/document/d/1GFvjZydw2yZfqT96WdCW3RVf2dTMBznYm1Nk6YpWJXo/edit?usp=sharing), where I argued that we could segregate the Docs, Glossary, and Urbit.org firmly and use a set of automated commits and exports to provide various targets for its content.

Docs workers would only have to work on Documentation. The workflow would automate creating Urbit.org subdirectories, .json files, and any additional deployment options we should ever choose to integrate going forward. I see a future where we might want a `man` agent that gets poked with terms and receives a definition, or to include a version of the documentation on Landscape, ships, etc. We need to keep these concerns cleanly apart to allow for their portability later.

## But usage documentation...

That said, the redesign's information architecture also pulled a variety of information out of the Docs and onto the site as *user-specific information* that didn't use the Docs templates.

Specifically, [/using](https://urbit.org/using/) and [/using/develop](https://urbit.org/using/develop/).

Docs has purview over these and it's not immediately clear to contributors that user manuals live on the site. Another protest is that this information shouldn't have been pulled out to begin with and should've lived in Docs. (I disagree, because users and developers are going to become different audiences rather quickly, but if there's an IA where that distinction is respected within the `/docs` folder, let me know.)

So in sum, these should probably live on the Docs repo — given that the docs goes into a "docs" folder, "using" goes into a "using" folder, and the submodule just imports all these subdirectories. What is an unknown for me is whether a Docs submodule that uses `/content` as its target folder could just dump its subdirectories and let the `/content/blog` live outside that submodule, or any other Urbit.org specific content.

If not, then perhaps the IA needs to be rethought to let it all live in, say, `/content/subdirectory` where `/content/subdirectory/docs` or `/content/subdirectory/using` live.

I open this for comment, and when I have a firm proposal, I will append one.

**Comment by kennyrowe** [comment]
It seems reasonable to me. Under this proposal would any links to existing content change? Or is that an implementation detail outside the scope of this issue?

**Comment by matildepark** [comment]
I guess the broader questions are a) whether we should just abolish the user/developer documentation distinction and fold it back into urbit.org/docs or not 

b) If not, how to enforce a separation of concerns for any contributors

Since it's confusing everyone to have it laid out like this; and it's inefficient to deploy.
