### ISSUE TITLE
Most of the content of gall.udon is mission

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit.org#37]
*missing. Compare:

https://urbit.org/docs/learn/arvo/arvo-internals/gall/

https://github.com/urbit/docs/blob/master/learn/arvo/arvo-internals/gall.udon

**Comment by vvisigoth** [comment]
Interesting. My guess is that that multiline block quote is causing some problems?

Try to render on ship and see if you get any difference, just to confirm that it's not an issue with |static.

**Comment by rmariani** [comment]
Looks like this has been fixed. Does anyone know what the problem was?

**Comment by ohAitch** [comment]
<s>vim typo</s>

**Comment by rmariani** [comment]
nice 😎

**Comment by ohAitch** [comment]
(Note: strikethrough because I'm just guessing, I was in no way involved
with gall.udon composition)
