### ISSUE TITLE
Update search engine to handle special characters.

### ISSUE THREAD

**Issue by sigilante** [urbit/urbit.org#373]
Urbit uses a lot of special characters, but the current search tool for the site ignores many of them.

For instance, if I search "@c", I receive pages on C runtime along with pages on the codepoint patp.

Since not all uses of runes like ";<" are co-incident with their verbal form "micgal", it is similarly hard to locate particular pages showing examples of use.

**Comment by matildepark** [comment]
Dependent on elasaticlunr used in Zola to be configurable, basically ... we bandaid fix'd this in part by appending a secondary glossary to "search in" (it only finds exact matches) but it can't encompass the entire search index.

See also the conversation in #148.

**Comment by matildepark** [comment]
This issue as filed is fixed but we don't cover atom types in the glossary. We should...
