### ISSUE TITLE
Scrollbar still weird

### ISSUE THREAD

**Issue by c-johnson** [urbit/urbit.org#38]
![image](https://user-images.githubusercontent.com/583272/51493114-0ab64600-1d69-11e9-99c1-48555eb49568.png)

**Comment by c-johnson** [comment]
(Chrome 71, wide screen size)

**Comment by flowerornament** [comment]
@jyng you got this?

**Comment by jyng** [comment]
Fixed this in latest commit: https://github.com/urbit/urbit.org/commit/f15703060c08ed929177b2df17f5058afc3c732a
