### ISSUE TITLE
Urbit on ARM

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#406]
`~botter-nidrul` has made some nice [tutorials](https://botter-nidnul.github.io/) on getting Urbit set up on the Raspberry Pi and Android. It would be great to incorporate this content into our docs. I almost submitted a PR adding a link to this under `content/using/develop.md#community-tutorials`, but that page is aimed at developers and this is something that any Urbit user may be interested in. I cannot find anywhere where we link to community tutorials other than that one spot though.

I recall that @benjamin-tlon also made a release build for the Raspberry Pi not too long ago. I see some references to an RPi build in the `urbit` repo Nix build scripts but do we have a compiled binary on `bootstrap.urbit.org`? I'm not sure how to find these. It should be linked on `content/using/install.md` though.

As for Android - since we don't have a build for it as far as I know, I think a link to `~botter-nidrul`'s tutorial is the right step for now.

**Comment by matildepark** [comment]
I think community tutorials is definitely the place. It’s offroad modding. I think it’s still @rmariani purview though.


—
~haddef-sigwen
https://urbit.org
