### ISSUE TITLE
Links to updates in /posts/index.html have wrong url: "/update/" rather than "/updates/"

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#43]
The generated website has the wrong links for updates on the /posts page. Wasn't able to locate the source of the bug at a cursory glance.

**Comment by flowerornament** [comment]
@vvisigoth on the current live site, I changed the urls manually in `/posts/index.html`

**Comment by vvisigoth** [comment]
Which branch of arvo did you use? I believe that static-site-dev has a
different version of the |static generator.
—
~poldec-tonteg
http://urbit.org

**Comment by flowerornament** [comment]
@vvisigoth I used arvo@static-site-dev

**Comment by vvisigoth** [comment]
Found the problem
https://github.com/urbit/urbit.org/blob/master/static-site/posts.hoon#L31

Not at my comp now, but change this line to 'updates' and you should be
good.
—
~poldec-tonteg
http://urbit.org

**Comment by flowerornament** [comment]
@vvisigoth ok, thought it might be that. I suspect this will also change the tag on /posts to "updates," which is undesirable.

**Comment by rmariani** [comment]
Fixed now
