### ISSUE TITLE
tar xzf urbit-vXXX.tgz results in zip:` stdin: not in gzip format

### ISSUE THREAD

**Issue by Byte1122** [urbit/urbit.org#438]
If you run linux (Ubuntu) and you following this tutorial: urbit.org/content/using/install.md
Than you could bounce to this error after running this:

> `curl -O https://bootstrap.urbit.org/urbit-v0.10.5-linux64.tgz
> tar xzf urbit-v0.10.5-linux64.tgz'

The result;

> `zip:` stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting `now`

Its maybe nice if someone can look at it, bc it's the first thing people will try out to run this nice piece of software on a server.

I solved it by download it on an other machine and unzip it there. Maybe it's combination of the use of Ubuntu and the use of the command "curl -O" with "tar xzf".

**Comment by matildepark** [comment]
@philipcmonk Would you be able to look into this?

**Comment by jfranklin9000** [comment]
I'm on Fedora 29, not Ubuntu, and I wasn't able to repro.
But I did get close:
```
curl -O https://bootstrap.urbit.org/urbit-v0.10.5-linux64.tgz
gunzip https://bootstrap.urbit.org/urbit-v0.10.5-linux64.tgz
tar xvf urbit-v0.10.5-linux64.tar
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
You tried to untar a gzip'd file that was already gunzip'd.
Maybe your download agent does that?  (Although that should
have changed the extension from `.tgz` to `.tar`.)

The instructions in https://urbit.org/content/using/install.md work for me.

**Comment by Byte1122** [comment]
thanks I am running ubuntu server focal, I changed some proxy things and network setting. I think it was something to do with curl more than tar xzf. Anyhow, it's now working!

**Comment by matildepark** [comment]
... well, I'm satisfied.
