### ISSUE TITLE
Site does not seem to compile with newer version of urbit/arvo

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#44]
We don't have enough information to write a good issue on this, and it takes forever to debug, but we attempted to build the website on @rmariani's machine using 0.7.2 and arvo@master or arvo@static-site-dev and it seems like the /docs folder was missing in the output.

This could also be a bug in the shell script we used.

**Comment by belisarius222** [comment]
Building the whole site at once has been known to cause a `bail:meme` (out-of-memory error), which can sometimes manifest as a hang instead. I believe @vvisigoth has a procedure for building it in two steps to use less memory.

**Comment by flowerornament** [comment]
Thanks @belisarius222 – that should be its own issue. I'll clarify this one to distinguish it.

**Comment by rmariani** [comment]
I am trying to build the static site on 0.7.2, and the problem seems to be that nothing is ever added to the /.urb/put directory. It's empty.

**Comment by vvisigoth** [comment]
Let me come over and check.

—
~poldec-tonteg
http://urbit.org

**Comment by flowerornament** [comment]
@rmariani what was the resolution?

**Comment by rmariani** [comment]
The issue turned out being that I forgot the argument `-A` to make it look for my arvo folder (which wa on the `static-site-dev` branch)
