### ISSUE TITLE
docs imported repo hasnt been updated since may 27

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#448]
Looks like the automated system took a nap, it currently points towards https://github.com/urbit/docs/tree/fa2f1ee67419e78504fed0da934b40f53664bf13

**Comment by matildepark** [comment]
It's not napping. From logs:

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

Fixing ...

**Comment by matildepark** [comment]
The adventures continue in https://github.com/urbit/urbit.org/commit/c56a484c721a8aafe6d0c1edf6f5c99b65580c39, as I find out what wiped my home directory / git config / keys...
