### ISSUE TITLE
Numbers on the docs sidebar are confusing

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit.org#45]
It's been mentioned here: https://github.com/urbit/docs/issues/378 and many other places.

Having numbers on the sidebar seem like a not-well-thought-out way to indicate the position of something in the hierarchy. The problem is that `Reference` being `4` is not something that actually means anything in the documentation. I'd say it's actually confusing, since it implies a progression that does not actually exist. `4 Reference` is not a continuation or outgrowth of `3 Learn`. 

Sometimes this is actively wrong where a numbering system is actually used in the ontology of the docs, such as in the case of of the Hoon tutorial; `1.3 The Subject and Its Legs` is listed on the sidebar as `2`.

My suggestion is that the position in the hierarchy is indicate things purely spatially, like this:

```
Reference
-Hoon Expressions
--Runes
---Atoms and strings
```

(there's definitely a better way to do it than by using hyphens. That's just for illustrative purposes)

**Comment by flowerornament** [comment]
@rmariani update on this: @friederjanmoerman will remove the numbers in the next version, and we have a new design for a subsequent version.

**Comment by rmariani** [comment]
Excellent!

**Comment by flowerornament** [comment]
Fixed
