### ISSUE TITLE
Clarify use of alternative desks.

### ISSUE THREAD

**Issue by sigilante** [urbit/urbit.org#476]
In "Using Your Ship," we read about syncing a friends `%experiments` desk to ours.

We can make a desk `|public` (although not documented here) but it's not clear how to sync that remote new desk to our ship.

There needs to be a worked example for both the remote and the local instances for syncing a new desk.

E.g.:

`~magbel` exposes a desk named `%starburst`.

To create this desk, I ran:

```hoon
|merge %starburst our %home
|mount /=starburst=
```

I then added the [Julia example generator `julia.hoon`](https://github.com/sigilante/julia) to the desk, committed the file to Clay, and made the desk public:

```hoon
|commit %starburst
|public %starburst
```

> My intent at this point was to synchronize the remote desk on `~magbel` to my own ship, which would look something like the following.  However, I've hit on an edge case of syncing a _new_ desk to a _new_ desk rather than an expected desk to an expected desk, and things aren't behaving quite as I anticipated.  I see a message about the synchronization but it's not doing what's intended yet.

Presumably to sync to my own ship's `%starfall` desk:

```hoon
|merge %starfall our %home  :: this is working to pre-create the desk
|sync %starfall ~magbel %starburst  :: but then this doesn't
```

Tagging @belisarius222 who generously weighed in and got me to this point.

**Comment by sigilante** [comment]
(N.B.  It does work, it's slow.  So what I suggest is adding the full example like the above to the documentation so both ends are clear.)

**Comment by tinnus-napbus** [comment]
no longer relevant with software distribution
