### ISSUE TITLE
Ames port instructions missing on hosting page

### ISSUE THREAD

**Issue by JohnELester** [urbit/urbit.org#512]
See https://urbit.org/using/operations/hosting/

The page mentions opening up the port in the firewall and setting a static Ames port when launching Urbit, but those details are missing.

-----

![ufw and ames port](https://user-images.githubusercontent.com/25461543/100548816-f680e100-323c-11eb-95b0-021508c0fc30.png)

-----

![missing the -p portnumber flag](https://user-images.githubusercontent.com/25461543/100548629-bbca7900-323b-11eb-8b20-7e62341cafd0.png)

**Comment by botter-nidnul** [comment]
Has been fixed, just awaiting approval #495

**Comment by baudtack** [comment]
Resolved.
