### ISSUE TITLE
Hosting Providers Section of Get Started Guide Needs To be More Concise

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit.org#610]
Specifically this section on how to set up your own Urbit on a cloud server should be moved to its own page so as to not appear to be a large wall of text, given that this page is oriented toward less technical people who do not want to run their Urbit themselves.

![image](https://user-images.githubusercontent.com/1377557/116258239-6470fc00-a73a-11eb-8c74-4e779179068f.png)

**Comment by matildepark** [comment]
Fixed in #1488
