### ISSUE TITLE
Base Get Started Page Should be Shorter and its Current Content Should Be Split into Multiple Pages

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit.org#611]
This planet/comet section should be the end of the page and should include links to go forward to a part 2.

Overall, I think this guide should be a 3-part document so that it is less a wall of text regarding things the user may or may not care about.

1. Get Started + Installating Urbit (download the command, installation, distinction between planets and comets) ->

2. Booting Guide (one page for planet, one page for comet)

2a. Planet Booting Guide
2b. Comet Booting / OTA setup Guide

(Both 2a and 2b move forward to page 3)

3. Using Landscape

![image](https://user-images.githubusercontent.com/1377557/116259366-5b345f00-a73b-11eb-9ea4-d95fcfb6581f.png)

**Comment by tylershuster** [comment]
I think this will probably undergo a total overhaul after Taisho hits 1.0.

**Comment by tacryt-socryp** [comment]
fixed in gold
