### ISSUE TITLE
add Urbit Community Dialogues to Events list

### ISSUE THREAD

**Issue by fischerando** [urbit/urbit.org#614]
As they're hosted in Urbit Community, would it be inappropriate to list the Urbit Community Dialogues on the Events page?

I understand that's easier said than done. However, there are lots of people who would be great fits for the network but (understandably) don't use Twitter, and without that it's hard to give a good glimpse of what kind of discussion exists on the network. Given the diverse topics and high-quality guests featured in the Dialogues, listing them on Urbit.org would go a long way to fix the issue. And while it might clutter up the calendar with nontechnical stuff, that might be a good thing, especially with hosting (and Taisho) making it even easier for nontechnical users to join on.

I'm a total github n00b but unless there are any strong objections, I'll try to pull together a rough pull request based on #606.

**Comment by galenwp** [comment]
This seems like a good idea to me

**Comment by matildepark** [comment]
These are no longer running.
