### ISSUE TITLE
Clicking and holding the menu button highlights the top-bar

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#65]
Clicking and holding menu button highlights the top-bar in Safari.

<img width="1440" alt="Screen Shot 2019-05-07 at 9 23 25 PM" src="https://user-images.githubusercontent.com/31774/57349323-84065880-710e-11e9-997a-2ca32b54924c.png">

**Comment by hardcodepunk** [comment]
Added `user-select: none;` and its prefixes to the header.
