### ISSUE TITLE
Font inconsistencies 

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/urbit.org#67]
I'm noticing quite a few type inconsistencies in this new version.

- We don't use work sans anymore.
- The docs don't use the correct weights for headers. The type scale can be found in our Indigo file on Figma.
- Since the Primer has switched to Inter, the encircled number discretionary ligatures no longer convert.

**Comment by flowerornament** [comment]
Thanks @gavinpatkinson. Assigning this to @friederjanmoerman and cc'ing @alexmatz.

- Where are you seeing work sans?
- I'll give @friederjanmoerman access to the type scales – we didn't make an attempt to match these in this revision, just a naive switch to InterUI
- How do you suggest we solve this? It looks like InterUI doesn't have the appropriate glyphs: https://rsms.me/inter/glyphs/ cc @jyng

**Comment by g-a-v-i-n** [comment]
Ok, seems like the stylesheet was cached, no more Work Sans on my end.

Thanks for sharing the Figma with him.

I would just use numbering like 1. 2. etc

**Comment by ohAitch** [comment]
(should there be a `contenthash` cache-busting filename for the CSS, or does the stylesheet change infrequently enough that it doesn't matter?)

**Comment by flowerornament** [comment]
@ohAitch I'd love that, personally cc @friederjanmoerman

**Comment by hardcodepunk** [comment]
Changing this to my suggestion would already style a lot to the right typography without me spending any time on it: https://github.com/urbit/indigo/issues/22

@gavinpatkinson 
Is it me or is it hard to determine the right typography parameters from this Figma file? I only see the font-sizes (also, two different numbers?). Is there a way to determine line-height, font-weight, margin and so on?

**Comment by jyng** [comment]
@friederjanmoerman I can help you out here. If you look in the right corner of the Figma file, there should be a "Code" tab and that should give your CSS equivalents( font-weight, font-size, and line-height) on the item you selected.

**Comment by hardcodepunk** [comment]
I had to make an account and log in to have the Figma functionality at my disposal.

The zola-port branch has been updated. Now the typography should follow the Indigo guidelines.
I also wrote a lil' vanilla JS script to style the input validation functionality. Now the newsletter `input` looks like the example in the Figma sheet:

![Screenshot 2019-05-13 at 00 54 12](https://user-images.githubusercontent.com/9070957/57588892-e2bb4000-751b-11e9-8ff7-62f10d20a0b8.png)

![Screenshot 2019-05-13 at 00 54 21](https://user-images.githubusercontent.com/9070957/57588896-e8188a80-751b-11e9-8d5f-068f621e9cda.png)

These changes have been tested in Safari, Firefox and Chrome on OS X. If anyone has Edge at its disposal, if you could check it out, that would be amazing. Anyone with an Android?
Styling forms and buttons can be fickle on the various platforms..

**Comment by hardcodepunk** [comment]
> I would just use numbering like 1. 2. etc

> `contenthash` cache-busting filename for the CSS

Live in zola-port branch.

**Comment by flowerornament** [comment]
@gavinpatkinson @jyng naively switching to Indigo typography significantly changes the website design https://deploy-preview-87--urbit-org.netlify.com/ https://github.com/urbit/urbit.org/pull/87. Was this the intention?

**Comment by flowerornament** [comment]
Turns out this implementation used XL-size headers, now parked in https://github.com/urbit/urbit.org/tree/indigo-typography. https://github.com/urbit/urbit.org/pull/100 merges a fix that seems good enough™, but could use review @gavinpatkinson @jyng

**Comment by flowerornament** [comment]
Closing this since should be taken care of by switching to Indigo
