### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by marisarow** [urbit/urbit.org#681]
When I click on 'Development channel in Landscape' link on https://urbit.org/ it opens a new tab with the url: about:blank. When I click out of the tab and return, only then do I see the url address update to 'web+urbitgraph://group/~bitbet-bolbel/urbit-community/graph/~darrux-landes/development'. This is unexpected behavior.

Expected behavior: Open Landscape with modal Join Group. 

I am using a mac with the latest version of chrome.

**Comment by drbeefsupreme** [comment]
This link doesn't seem to be on urbit.org anymore (or at least not the front page, which is what I think this is about).
