### ISSUE TITLE
Latest grants page implementation doesn't tell me anything about what proposals, bounties and apprenticeships are

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#683]
The Grants page `/grants` is missing some content which explains what each program offers. 

This is the current page's implementation (zoomed out):

<img width="650" alt="Screen Shot 2021-07-19 at 1 27 42 AM" src="https://user-images.githubusercontent.com/1195363/126107523-25267552-2bc6-4680-8123-5dd0278865db.png">

This is the current page's information:

<img width="804" alt="Screen Shot 2021-07-19 at 1 27 16 AM" src="https://user-images.githubusercontent.com/1195363/126107524-9a7d6307-14bc-4a4c-a0ea-33bf0e117d86.png">

See the current `https://urbit.org/grants/` page to see the discrepancy directly.

**Comment by matildepark** [comment]
I believe they do now!
