### ISSUE TITLE
Design: Rethink the Blog + Events section

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#684]
https://user-images.githubusercontent.com/1195363/126109213-cc2822ae-9904-4f21-8922-b126b8a846ac.mov

Currently, the "Header as Toggle" is a little confusing, and not immediately apparent as a clickable element. 

We should design a section (or sections) that clearly depict both blog posts and events in a clarified manner.

Some related fixes that should be solved along with this work:

- Fix: I expected that clicking Events Tab on the Home Page should show you the same structure of the Events Page (Coming Soon/Past Events)
- Fix: Events on the front page do not have dates, so it's impossible to know which events are past, present, or forthcoming

Josh note: 
> "I’d rather show events by default than blog posts, as events are more interactive, assuming we need to pick one"

**Comment by urcades** [comment]
This work may be semi-dependent on metadata being fixed a la #712

**Comment by urcades** [comment]
A pretty "dumb" take on how to simply unfold each section for visibility, nothing fancy here:

![Screen Shot 2021-07-22 at 3 34 47 AM](https://user-images.githubusercontent.com/1195363/126604199-95b5965b-3f6d-442e-8a20-54085b30c543.png)

Each CTA under the respective row leads to the post index page of both blog and events. I was thinking pretty roughly that for each event, maybe we surface up RSVP buttons within each card.

On a related note:

As I was thinking about this more, in whatever next iteration of the site we put out, there's really no need for these sections on the front page, if they're well-situated in an obvious-to-use top nav. _New_ Blog posts and Events, if important enough, should really be surfaced up within the hero, or located as an extension of it.

**Comment by tirwyd-sarmes** [comment]
Big fan of the unfolded Blog and Events section. When I spoke with @g-a-v-i-n a month ago we thought about having the events section not using cards on the home page, maybe more of a horizontal "list" view with standardized mini-cards or something.

**Comment by g-a-v-i-n** [comment]
Looks good, working on this now

**Comment by g-a-v-i-n** [comment]
surfacing RSVP button only seems to make sense when the event is in the future - what do we want to do with past events? I am defaulting to hiding the RSVP button.

**Comment by urcades** [comment]
Yeah, good point — there's no need to RSVP for past events.

—
~fabled-faster
https://urbit.org/

**Comment by g-a-v-i-n** [comment]
https://urbit-org-8sxjpfuk7-urbit.vercel.app

PR: https://github.com/urbit/urbit.org/pull/738

**Comment by g-a-v-i-n** [comment]
Hmmm where did the lefthand nav come from? @matildepark 

<img width="1338" alt="Screen Shot 2021-07-28 at 1 48 07 PM" src="https://user-images.githubusercontent.com/5265021/127393803-1219f0f2-1013-417d-9220-ceab47046346.png">

**Comment by matildepark** [comment]
TableOfContents component inserts a nav on any page. It was introduced at @jalehman's request yesterday.

**Comment by g-a-v-i-n** [comment]
it messes up layout

**Comment by g-a-v-i-n** [comment]
too many people working on this page rn. needs design input

**Comment by matildepark** [comment]
I don't really feel strongly about it, I just put it in for him. It's yours

**Comment by g-a-v-i-n** [comment]
Resolved in #738
