### ISSUE TITLE
Youtube embed styling is off

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#69]
- Remove border styling
- Make width Youtube default

<img width="745" alt="Screenshot 2019-05-08 15 8 28" src="https://user-images.githubusercontent.com/31774/57411684-27a14880-71a3-11e9-9019-ca105d6d01b0.png">

**Comment by hardcodepunk** [comment]
I added a custom 'youtube.html' shortcode overriding the zola default one. The custom one wraps the iframe in `<div class="video-wrapper"></div>` which I have styled for the iframe to act responsive to resizing and obviously at 100%. Border has been removed with a `border: none;`.

I don't know if I should link the branch/commit but I pushed it onto the zola-port branch of the urbit.org repo.
