### ISSUE TITLE
Copywriting: Most docs copy could use less prose-like language + less resulting length

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#699]
This is ultimately up to the UF, but in the latest round of feedback for the urbit.org refresh, it was noted that the style of writing for the majority of Urbit's documentation is lengthy, tends towards prose, and overall results in incredibly long pages.

This is understandably a longer-term, and very involved project, but we should consider updating + refining the writing style used across docs to become more pithy, to-the-point, and abbreviated when it's warranted.

**Comment by matildepark** [comment]
The docs have since been basically rewritten, restructured, and split out per audience (everyday people, power users, developers).
