### ISSUE TITLE
Bold text is italic in posts content

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#70]
Text that was meant to be bold is italic. This may also be true about docs content, but I haven't found an obvious example yet.

<img width="327" alt="Screenshot 2019-05-08 17 3 5" src="https://user-images.githubusercontent.com/31774/57416014-2b3ccb80-71b3-11e9-8742-b5ec73c96fec.png">

**Comment by ohAitch** [comment]
Sounds like * should be translated as ** or sth, as per the previous
discussion on udon being a broken incompatible take on markdown?

**Comment by flowerornament** [comment]
@ohAitch yeah, either that or it's _ vs. */**.

**Comment by ohAitch** [comment]
`*` is the udon one for bold, also see like [the files in question](https://raw.githubusercontent.com/urbit/urbit.org/25da64818150c7557eb875609909737136be7e6c/content/posts/2018-3-24-update.md).

**Comment by jfranklin9000** [comment]
I take it Sail syntax should be removed from udon files that were converted to md (`using/shell.md` for example)?

**Comment by flowerornament** [comment]
@jfranklin9000 yes! I took a pass at this yesterday, but looks like I missed some spots with my REGEX.

**Comment by ohAitch** [comment]
galaxy brain: write a .udon AST renderer that outputs as markdown

(though like actually rendering to html and then pandoc'ing back to md
would probably have been more reliable than regexen?)

**Comment by flowerornament** [comment]
🤯

**Comment by flowerornament** [comment]
@jfranklin9000 @ohAitch @rmariani if you want to take a shot at this and other recent issues related to the urbit.org reimplementation (here and in /docs), please feel free

**Comment by jfranklin9000** [comment]
I'll take a shot at it.

**Comment by flowerornament** [comment]
This issues is still at-large and an easy fix for the intrepid REGEX user

**Comment by urcades** [comment]
@matildepark I feel like we can close this one...

**Comment by matildepark** [comment]
This issue is still at large, actually. See all the names [here](https://urbit.org/updates/2018-7-20-update/).
