### ISSUE TITLE
Improved + heightened separation between "Developer Documentation" and "Urbit Usage Documentation"

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#701]
We need an improved + heightened separation between "Developer Documentation" and "Urbit Usage Documentation". 

As it stands, it's confusing to colocate how to use Landscape + Urbit Userspace and how to use Urbit as a technical system. People who are interested in learning how to use Landscape shouldn't need to worry about what a binary is, or what Nock, Arvo, and Hoon are.

This boils down to however we end up redefining the IA of the site, with respect to the channels of communication we want to lean into.

**Comment by tinnus-napbus** [comment]
there is now a separate site for developer docs
