### ISSUE TITLE
Comms: Youtube Cover Art Normalization/Simplification, keep visual structure similar to events?

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#706]
The way we design these cover images needs to be rethought:

<img width="1137" alt="Screen Shot 2021-07-19 at 12 08 32 PM" src="https://user-images.githubusercontent.com/1195363/126191877-bf75bfe7-9623-4cf7-936e-e11d1e171519.png">

This is a project that may be best suited for integrating into a comms work schedule (which doesn't exist on GitHub), but in order to rectify some of the changes we're making to the display of event + blog + update imagery on urbit.org, we'll need to re-assess the design of Urbit's youtube cover art.

This project is related to #689 , because we'll need to think about the urbit.org presentation of any new image-making directions we establish.

**Comment by gordoncc** [comment]
More legible thumbnails have been designed and will be deployed from here on out
