### ISSUE TITLE
Completely revise the IA for Urbit Documentation

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#707]
We should revise the information architecture for Urbit Documentation, oriented around types of developer activity, technical structures, learning paths, etc. — this restructuring should directly follow from what we believe to be the most important groups of people we need to communicate with.

A primary task of this project will be to establish existing or desired "developer archetypes" that content restructuring can revolve around, i.e. if we're prioritizing onboarding developers for "application development", we may need a docs structure that surfaces up Airlock and inter-language/environment development patterns more explicitly, which we currently only do minimally.

**Comment by g-a-v-i-n** [comment]
Chiming in to +1 this. There are multiple issues with the docs organization we cannot just design away.

For example, there are many different ways individual pieces of documentation have been organized, which then bubble up to the righthand table of contents sidebar. Sometimes this sidebar helps, other times it does not, as demonstrated below.
<img width="1264" alt="Screen Shot 2021-07-28 at 2 45 41 PM" src="https://user-images.githubusercontent.com/5265021/127401779-cd44a799-cedb-40f2-85b3-b21991289038.png">
<img width="1263" alt="Screen Shot 2021-07-28 at 2 45 33 PM" src="https://user-images.githubusercontent.com/5265021/127401782-163bd5f8-ef11-4849-b53e-f00221a63c6a.png">
<img width="1261" alt="Screen Shot 2021-07-28 at 2 46 11 PM" src="https://user-images.githubusercontent.com/5265021/127401774-dd6ece79-d197-49d1-b7fe-ef340de2540f.png">

**Comment by gordoncc** [comment]
developers.urbit.org, oh yeah
