### ISSUE TITLE
Design: Improved Grants List filtering/search/application UX

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#708]
The current Grants list filtering experience:

<img width="1370" alt="Screen Shot 2021-07-19 at 1 00 52 PM" src="https://user-images.githubusercontent.com/1195363/126198530-40632a32-e067-4b9c-aa52-f3d2964e7f29.png">

As Grants becomes an increasingly populated and trafficked interface, we're likely going to need to develop a more rich means of searching, filtering, and viewing the state of grants. 

Additionally, we'll likely need to transition this page into more of an editorial/messaging surface, and consolidate the grants interfaces into a more app-like interface.

**Comment by matildepark** [comment]
There's more filters now — in progress, completed, etc.
