### ISSUE TITLE
"Editorialize" the Grants page

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#711]
Editorialize the Grants section of the site (`https://urbit.org/grants/`), highlighting more stories about Urbit app/agent/core development, ongoing stories about the developer community, etc. 

Add a new Gifts Section, telling the story of how off the cuff gifts are granted to conspicuously useful people, people who add to the culture of the network, etc. — emphasis on non-technical contributions

**Comment by matildepark** [comment]
I believe we have satisfied this.
