### ISSUE TITLE
Events, on both the front page and on the actual `/events` page, should surface up a more obvious RSVP/event attend link as a main CTA

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#712]
At the moment, events cannot be directly RSVP'd to

We should consider implementing an additional "Event RSVP URL" metadata field which adds a button to an event component for quick RSVPing.

**Comment by matildepark** [comment]
@tirwyd-sarmes Can you work with @g-a-v-i-n on amending the events data structure here?

**Comment by g-a-v-i-n** [comment]
Resolved in #738
