### ISSUE TITLE
[docs] Page trees should have an index that's navigated to upon first click

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#713]
via @jalehman 

> It's not this way on the current site, but it should be.

**Comment by urcades** [comment]
The implementing team is contesting this particular issue

**Comment by jalehman** [comment]
That's fine, although there are many places in the docs where we put (debatably) useful information like this: https://urbit.org/docs/system-overview/

Usually it serves as an overview of the contents of each subdirectory, but I'll admit that the quality of these overviews is hit or miss. The current structure, where we have content in URLs that cannot be reached through the interface, is ambiguous and frustrating though. It'd be nice if that were solved, and this is the clearest way I can think to do it.

—

~wolref-podlex
https://urbit.org ( https://urbit.org/ )

**Comment by matildepark** [comment]
My main counter-example is, imagine you want to go to 2c of the standard library in Hoon.

Hoon -> refresh
Reference -> refresh
Standard library -> refresh
2c -> refresh

—
~haddef-sigwen
https://urbit.org

**Comment by g-a-v-i-n** [comment]
Adding that part of the opposition to this is opening or exploring the tree navigation would navigate you away from your current page. As a reader I could not remain on my current page while opening subdirectories.

**Comment by g-a-v-i-n** [comment]
If we flattened the IA of the docs and constrained the depth to 2, I would be more open to this. For example

**Arvo**
subItem
subItem
subItem
**Azimuth**
subItem
subItem
subItem
...

We could also add more depth by extending the length of each page. For example: https://nodejs.org/dist/latest-v14.x/docs/api/buffer.html

**Comment by matildepark** [comment]
This is now the case on urbit/developers.urbit.org, so maybe we just port it here — a possible case for packaging this entire layout into urbit/foundation-design-system ...

**Comment by matildepark** [comment]
Though ... on second thought, we no longer even have a nested docs layout on this site! So, it can be closed anyway.
