### ISSUE TITLE
Fix the /using and /getting-started sidebars

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#716]
The two pages: 

- https://urbit-org-gold.vercel.app/getting-started
- https://urbit-org-gold.vercel.app/using 

both require fixed/improved sidebars to properly render the contents of each section — currently they feel a little broken or "missing" something, possibly due to their nature of being docs-but-not-docs

**Comment by matildepark** [comment]
Can you be more specific about what should be altered?

**Comment by urcades** [comment]
Yes, definitely! I was really just setting this up as a placeholder, going to substantiate it momentarily.

The main issue here is that the 'root' of the page (the one you land on, if you click the links above) isn't displayed in the sidebar, so one feels slightly displaced when landing on the page.

I was going to reference the sidebar used for Docs proper, and try and implement these pages similarly.

**Comment by urcades** [comment]
So, I tried actually muddling around in the code to no effect. This is essentially what I'm getting at needs to be changed. The current  state of the sidebar for each respective page:

![Screen Shot 2021-07-25 at 2 38 31 AM](https://user-images.githubusercontent.com/1195363/126890168-f1e2c581-f4e7-4986-beb9-82295a0373ac.png)

What I was trying to prod it into displaying:

![Screen Shot 2021-07-25 at 2 38 23 AM](https://user-images.githubusercontent.com/1195363/126890184-ba93f200-faec-4961-a00f-ae5e64652497.png)
