### ISSUE TITLE
Events: Coming soon button not clickable. Is it even a button?

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit.org#718]
<img width="1140" alt="Screen Shot 2021-07-26 at 2 18 44 PM" src="https://user-images.githubusercontent.com/1377557/127046135-e5075ac5-295e-4b98-a60b-fdfaaa685ee5.png">

**Comment by matildepark** [comment]
It isn't. @urcades should we separate out what 'button' and 'subheader' styling is in this respect?

**Comment by urcades** [comment]
This element is definitely intended to be something like a "special" header (a label), not an interactive element — we could definitely do with making these a little more diminutive, less overlapping with interactive elements. I'll give this one some thought soon.

**Comment by urcades** [comment]
I just edited the headers down to look less interactive, more like subheaders. Boring but obvious:

![Screen Shot 2021-07-27 at 11 47 08 AM](https://user-images.githubusercontent.com/1195363/127185354-6e3492ee-8eb7-4331-8706-6a136cc97349.png)
