### ISSUE TITLE
Font-size in lists is smaller than body

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#72]
Size should be the same in lists

<img width="874" alt="Screenshot 2019-05-09 11 32 35" src="https://user-images.githubusercontent.com/31774/57477735-3133ba80-724e-11e9-801b-d1805acbd037.png">

**Comment by hardcodepunk** [comment]
Adjusted in the zola-port branch. Didn't know if I was allowed to pick this one up. Saw the unassigning too late.

Note: I removed the .posts and .docs classes and changed the encompassing `<div>`s to `<article>` tags and styled the `<p>` and `<li>`s subsequently as seen in the indigo stylesheet.
