### ISSUE TITLE
Broken image on Urbit ID page

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit.org#721]
https://urbit-org-gold.vercel.app/understanding-urbit/urbit-id

This image link is broken: https://media.urbit.org/site/understanding-urbit/urbit-id/urbit-id-address-space-1.svg%22

Could be a typo with that %22?

**Comment by urcades** [comment]
Yeah, when I check out the actual source, we see this:

![Screen Shot 2021-07-27 at 11 19 29 AM](https://user-images.githubusercontent.com/1195363/127180909-38c857f5-fd68-45b8-b8c4-38715e533ffb.png)

This image's url actually works when clicked through — are we processing images somehow and breaking the media reference?

**Comment by urcades** [comment]
It's also actually in GCP, so I don't believe this is a missing asset issue:

![Screen Shot 2021-07-27 at 11 19 29 AM](https://user-images.githubusercontent.com/1195363/127181313-849ca3c9-eb5a-420e-a8b7-b03686ad72f3.png)

**Comment by urcades** [comment]
Ah, I see what's going on

**Comment by matildepark** [comment]
You just remove the `"` I believe

**Comment by urcades** [comment]
I believe I fixed the issue: https://github.com/urbit/urbit.org/commit/7af2a5c9d2d36a2193a35951544eb06e5212441d

For some reason, there was a `"` appended to the image link.

Unsure if I need to rebuild the preview site or if it'll deploy with the last pushed commit, but it should be back to normal.

**Comment by matildepark** [comment]
It just deploys itself each commit — thanks!
