### ISSUE TITLE
Grants: Tags look like buttons, but do not act like buttons. 

### ISSUE THREAD

**Issue by jalehman** [urbit/urbit.org#726]
Can we change UI to look less interactive? OR Make them interactive.

**Comment by jalehman** [comment]
I see that buttons are more square, where tags are more pill-like, but they are indeed similar. @urcades or @g-a-v-i-n, can either of you weigh in on this?

**Comment by urcades** [comment]
@jalehman Yeah, the actual cards themselves definitely need some work — will get a simple refactor of these folded in soon

**Comment by g-a-v-i-n** [comment]
It would be nice to refactor this soon because of #739

**Comment by matildepark** [comment]
Stale, I don't believe this is relevant anymore
