### ISSUE TITLE
Long article titles wrap, which can cause confusion

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit.org#729]
<img width="239" alt="Screen Shot 2021-07-28 at 9 25 39 AM" src="https://user-images.githubusercontent.com/9275716/127330232-38968dcc-2dd2-444f-ac8b-222c021f4991.png">

See above image. "Overview" seems to be a new section, where actually its just a part of the article "Data Structure Overview"

**Comment by matildepark** [comment]
It’s just wrapping. Is it better to truncate them?

**Comment by ynx0** [comment]
Not feeling super strongly but yeah I think so. Just because it really does look like a new section to me which truncation would definitely clear up. Or, pushing the wrapping so that it would at least be in-line with the content before it.

**Comment by ynx0** [comment]
It also just looks kinda weird here:
<img src="https://user-images.githubusercontent.com/9275716/127332870-2eae7b84-130f-482f-add7-c00072af4736.png" width="200px">

**Comment by matildepark** [comment]
> Not feeling super strongly but yeah I think so. Just because it really does look like a new section to me which truncation would definitely clear up. Or, pushing the wrapping so that it would at least be in-line with the content before it.

Oh interesting; this may be doable by just making the `<li>` inline-blocks

**Comment by ynx0** [comment]
Oh yeah, idk how it will actually look, but if you do decide to make them inline, maybe giving slightly more space between different title, or slightly squeezing together words within the same title would help differentiate between them better.

**Comment by ynx0** [comment]
One piece of justification for the squeezing of a wrapped title / giving it space is:
<p align="left"><img src="https://user-images.githubusercontent.com/9275716/127363193-3c36cc7b-e988-4e6c-9469-5aad09c175ea.png" width="200px"></p>

Because my headers are admittedly quite long, they seem to meld together into one blob
