### ISSUE TITLE
Old anchor links for certain runes don't work

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit.org#732]
For instance, when you navigate to https://urbit.org/docs/hoon/reference/rune/wut#overview

The following links to runes no longer work, because they refer to anchors `#wutpam` and `#wutbar`, while the new anchors seem to be `#-wutpam` and `#-wutbar`
![image](https://user-images.githubusercontent.com/9275716/127332404-5c5a895a-63f7-455e-956e-adb2823c87c2.png)

![image](https://user-images.githubusercontent.com/9275716/127332685-b4c35138-28e0-4088-9c80-5e95f2f26203.png)

**Comment by matildepark** [comment]
This can be fixed by adding `{#wutpam}` etc at the end of the headers to specify an id; the new markdown renderer appears to care about the code block in the title so it adds a -

**Comment by tinnus-napbus** [comment]
has been fixed
