### ISSUE TITLE
<tags> enclosed in single backticks aren't escaped

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit.org#742]
```
`<foo>`
```

gets treated like html, only triple backticks actually escape them. Annoying cos sometimes you want inline code snippets with `<stuff>`

**Comment by matildepark** [comment]
Escape them with `\`

**Comment by ohAitch** [comment]
does \`inline\` code also eat backslashes then??

**Comment by tinnus-napbus** [comment]
> Escape them with `\`

that doesn't work

**Comment by tinnus-napbus** [comment]
```
`\<foo>`
```
 and
 ```
 `\<foo\>`
```
 render as `\`

**Comment by ohAitch** [comment]
Looks like next.js uses `remark`, which claims to be commonmark spec-compliant - and certainly this seems to work in raw remark: https://q84s6.csb.app/

**Comment by matildepark** [comment]
Oh, I see now, I escaped this with html entities. https://raw.githubusercontent.com/urbit/urbit.org/master/content/docs/system-overview/arvo.md

I think it’s because we inject the markdown string as html, or something. 

— 
~haddef-sigwen
https://urbit.org

**Comment by tinnus-napbus** [comment]
oh wait it has the same problems in the triple-backticked blocks too. See the h1 hello worlds in the code blocks here: https://urbit.org/docs/arvo/eyre/examples#direct-http-handling-with-gall-agents

should I go through this stuff and replace all tags with entities or can this be fixed?

**Comment by ohAitch** [comment]
Entities also [shouldn't work](https://qmtq0.csb.app/), though it's consistent with the page being double-parsed as html - presumably the parser _produces_ `<code>&lt;code words&gt;</code>` and then that gets "rendered" and re-rendered

**Comment by tinnus-napbus** [comment]
this appears to have been fixed by the vercel dependency fix
