### ISSUE TITLE
tables should have borders and such

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit.org#744]
tables currently look really bad. There's barely any padding and no borders and such (see https://urbit.org/docs/arvo/eyre/external-api-ref#poke)

they should look basically exactly how github does them:

|foo|bar|baz|
|--|--|--|
|blah|blah|blah|
|blah|blah|blah|
|blah|blah|blah|
|blah|blah|blah|
|blah|blah|blah|
|blah|blah|blah|

**Comment by g-a-v-i-n** [comment]
Resolved in #747
