### ISSUE TITLE
what is text-transform: lowercase for?

### ISSUE THREAD

**Issue by jyng** [urbit/urbit.org#75]
@friederjanmoerman 
In `/sass/_main.scss/` line 347, I'm seeing
```
.h-font {
  text-transform: lowercase;
}
```
I'm not aware of anywhere where we are strict about lowercase. In most cases, we just make sure we use lowercase in the markup. Thoughts?

**Comment by hardcodepunk** [comment]
The email newsletter subscribe button is an example. I copied the design as best as I could from the previous site version as I was briefed. Also in the Primer apparently, which I blindly copied pasted into the zola port and just made it work.
Also the taxonomies of the posts have h-font applied.

**Comment by jyng** [comment]
Yeah for that I would just declare that in the markup. h-font was used previously to explicitly style a piece of text to use Work Sans (header font). We don't use Work Sans anymore so I vote for removing this class.

**Comment by jyng** [comment]
Also, could you share me with the designs you were given? I'm just starting to dig into reviewing the work here and would like to get up to speed. Thanks!

**Comment by flowerornament** [comment]
@jyng @friederjanmoerman has been working off the old live site. Let me know if you need a build, since it's no longer online.

**Comment by hardcodepunk** [comment]
The taxonomy name gets generated by the engine. Capitalized. So essays would be Essays if I didn't add this class in for example `posts/list.html`.
