### ISSUE TITLE
code snippets not wrapping

### ISSUE THREAD

**Issue by hardcodepunk** [urbit/urbit.org#77]
`<pre>` tags aren't wrapping.

![Screenshot 2019-05-10 at 11 54 53](https://user-images.githubusercontent.com/9070957/57518921-7f15f480-731a-11e9-8931-26213b3f0123.png)

I could style it with `overflow-y: scroll;`
![Screenshot 2019-05-10 at 11 57 01](https://user-images.githubusercontent.com/9070957/57519049-c13f3600-731a-11e9-8b3d-f4205158adfe.png)

Or white-space: pre-wrap;
![Screenshot 2019-05-10 at 11 58 11](https://user-images.githubusercontent.com/9070957/57519128-eb90f380-731a-11e9-9406-c860328ccc1b.png)

But I would suggest the first option because the latter is confusing in my opinion as it wraps to the next line which looks like perhaps another command.

**Comment by Fang-** [comment]
> But I would suggest the first option because the latter is confusing in my opinion

+1! Expected behavior for `<pre>` is to display the text as literally as possible, which definitely includes not wrapping it!

**Comment by hardcodepunk** [comment]
It's ready in the zola-port branch.

**Comment by ohAitch** [comment]
though separately, adding a backslash-escaped line break or two to the offending line might be good
