### ISSUE TITLE
hoon syntax highlighter doesn't handle escaped double-quotes in tapes

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit.org#770]
if you have a tape in some hoon code like `"blah\"blah"`, it doesn't treat the middle double-quote as being escaped, so it ends the tape there, then starts a new tape at the next one that swallows the rest of your code.

**Comment by matildepark** [comment]
PR'd to upstream Prism dependency - https://github.com/PrismJS/prism/pull/3473

Closing as not relevant to this repo, when we update the dependency this will be remedied. But you can see here it works:

before -
<img width="780" alt="Screen Shot 2022-06-13 at 7 10 40 PM" src="https://user-images.githubusercontent.com/20846414/173479635-b0e0e0b6-0956-4c8f-b4fa-f20fc091a595.png">

after -

<img width="753" alt="Screen Shot 2022-06-13 at 7 10 30 PM" src="https://user-images.githubusercontent.com/20846414/173479655-5ecb447c-deec-4922-8414-20141e4ffca3.png">
