### ISSUE TITLE
urbit.org-wide search capability doesn't appear to work

### ISSUE THREAD

**Issue by urcades** [urbit/urbit.org#778]
When invoking search using Cmd+K, I'm able to retrieve a list of results, but clicking into an item just closes the search without navigating to a new page.

cc @g-a-v-i-n : Going to initially assign to you because of the search refactor stuff you've been working on, feel free to send this over to someone else to fix

**Comment by g-a-v-i-n** [comment]
Thanks, on it

**Comment by g-a-v-i-n** [comment]
Patched in #779
