### ISSUE TITLE
graph-store docs duplication

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#794]
We currently have both https://urbit.org/docs/userspace/graph-store/overview and https://urbit.org/docs/userspace/landscape/reference/graph-store . The latter is (apparently) out of date, less informative, and repeats some of the same information as the former (but is also not entirely contained by it). I don't think we need both - the latter ought to be updated and merged into the former.

**Comment by tinnus-napbus** [comment]
landscape section has been removed
