### ISSUE TITLE
Links that are also formatted as code do not look like links

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit.org#803]
Example: https://github.com/urbit/docs/blob/master/userspace/graph-store/validator-walkthrough.md#earthmars-interface-details, which renders fine on github but not on urbit.org.

Compare github:

<img width="619" alt="Screen Shot 2021-07-24 at 9 36 34 AM" src="https://user-images.githubusercontent.com/9275716/126870135-e3ccd8b0-5873-4d82-a4ff-0a26cacf1e2d.png">

with urbit.org:

<img width="619" alt="Screen Shot 2021-07-24 at 9 33 33 AM" src="https://user-images.githubusercontent.com/9275716/126870068-3edc6020-b891-4db4-a88a-1a78176775d4.png">

**Comment by tinnus-napbus** [comment]
this appears to have been fixed at some stage:

![2021-09-16_23h06m40s](https://user-images.githubusercontent.com/77721746/133601540-50cb28b7-513d-4028-960b-5ea91d7d4c34.png)
