### ISSUE TITLE
Friends of FizzBuzz exercise two is unfair :)

### ISSUE THREAD

**Issue by bvschwartz** [urbit/urbit.org#808]
This is the one where you have to figure out how to pass two parameters to a gate. I believe the answer is just

```
|=  {start/atom end/atom}
```

(Maybe there is a better way?) However it is not clearly documented in the hoon docs as far as I can see. I suppose it can be figured out by implication. Perhaps the syntax section should talk about the syntax for creating some basic things like numbers, strings, cells/tuples, and whatever you call the {} construct. I don't think the {} syntax is ever discussed.

[edit: ignore this part about comments as it is already there] This should probably be a separate issue: but it would be really nice if there was a comment section at the bottom of each page for a lower friction way of providing comments.

**Comment by galenwp** [comment]
No problem!  I should say, we have been working through some issues with the comments.  More on that tomorrow.
