### ISSUE TITLE
Post header not lined up

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#81]
Post content isn't quite lined up with the top of the menu button.

<img width="415" alt="Screenshot 2019-05-13 16 59 13" src="https://user-images.githubusercontent.com/31774/57661614-80585300-75a0-11e9-9e59-f28fb59c74fe.png">

**Comment by hardcodepunk** [comment]
Lined up correctly (removed `mt2` class from the date) in zola-port branch.

**Comment by flowerornament** [comment]
@friederjanmoerman I broke this again and then just removed the dates

**Comment by hardcodepunk** [comment]
I think this one is okay now? Unless you want the dates added again?
