### ISSUE TITLE
User reported that the mailing list signup form doesn't work on Mobile Safari (iPad)

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#83]
A user reported that the mailing list signup form didn't work for them on Mobile Safari (iPad). Confirmed that the form works for me in Chrome and there have been a handful of signups over the past few days.

**Comment by alexmatz** [comment]
can you please fix this one first @friederjanmoerman?

**Comment by alexmatz** [comment]
looks like there's two issues here. 1. mobile safari/ipad is broken. 2. we just do not have any visual confirmation for users after they submit their email (i'll make another issue for this)

**Comment by hardcodepunk** [comment]
_SSL certificate isn't recognized as 'safe'_ need to be fixed first #109

**Comment by galenwp** [comment]
My comments from #109 are more relevant here. This is likely simply because we don't give user feedback on clicking subscribe, which is quite confusing. This is easy to test on desktop. Not sure what's up with iPhone 5 not understanding our cert.

**Comment by friederjanmoerman** [comment]
@msutherl Can you mail me the original mailchimp subscribe code snippet from your mailchimp account, I do not have access to it? I'm suspecting something went wrong styling it. I want to debug the styled form because before it was working fine.
