### ISSUE TITLE
Old post links are broken

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#84]
Posts used to live at i.e. `urbit.org/posts/essays/title/`, or generally `urbit.org/post/[category]/title/`. I just noticed that this changed in the re-implementation.

@friederjanmoerman would it be easy to move the posts into category folders and modify the templates slightly, or is there a good reason it's set up this way?

If the latter, we'll need to set up redirects for all of the old posts.

**Comment by hardcodepunk** [comment]
It was easy to get the taxonomy out of the post metadata but this disadvantage you just pointed out kinda weighs out my positive. I'll give it a try.

**Comment by flowerornament** [comment]
Alternatively we can add aliases to the metadata. I did this for a few posts already.

**Comment by hardcodepunk** [comment]
There is also the option to just search the whole content folder for `/posts/` links and change them subsequently to the correct format. I didn't encounter that many or am I mistaken? I don't think it'll take me a long time to correct 'em all. I think setting up redirects 'll take more time. The most time consuming option is rewriting templates.
Unless you see more advantages in having the different post categories split into different folders for each category.

**Comment by ohAitch** [comment]
I'm assuming this mostly concerns inbound external links, not ones in the
docs themselves?

**Comment by flowerornament** [comment]
@ohAitch @friederjanmoerman that's correct – I'm referring to external links i.e. on Twitter.

**Comment by hardcodepunk** [comment]
The lesser time consuming option would be making aliases for each and every 'old' post.
But it does make sense to have an essay live at `posts/essays/..` for the sake of having clear url slugs. The Zola taxonomy functionality doesn't create a slug like that, sadly enough.

What do you think?

**Comment by flowerornament** [comment]
@friederjanmoerman I'd much prefer to have the slugs with categories. Can you see how that might be possible and let us know what the downsides might be?

**Comment by hardcodepunk** [comment]
I've been trying to get the subsection title and permalink where I was able to call the taxonomy term before. It's possible when I call on all posts in the main _index. But on a subsection page it's not possible. I was thinking of adding 'extra' info per post, a bit like a taxonomy term, but I'm still checking how I can return it per post. Not sure if it's possible at all in general.

So for now in the `reorganize-posts-slug` branch everything works as you proposed, but the taxonomy term is missing in the post preview in the posts listing on a category page. I guess this counts as a downside for now.

**Comment by flowerornament** [comment]
Thanks @friederjanmoerman, will check this out

**Comment by matildepark** [comment]
Overhauled site has redirects and aliases for slugs going back several years (I checked our old tweets for all slug formulations). If anyone finds something I missed, ping and I'll reopen.
