### ISSUE TITLE
Change all links to zola internal links

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#85]
`zola` has a format for internal links, just i.e. `./posts/essays/post/` – including the `.` at the beginning. This allows zola to check that internal links haven't broken.

https://www.getzola.org/documentation/content/linking/

It would be good to convert all internal links to this format.

**Comment by hardcodepunk** [comment]
All doc internal links have been updated and checked. Pushed to the zola-port branch of the docs submodule.
