### ISSUE TITLE
Delete Expressions doc?

### ISSUE THREAD

**Issue by joshuareagan** [urbit/urbit.org#860]
I've been looking over Hoon docs and making some revisions.  With the latest changes to Hoon and some distinctions Curtis has made (e.g. value/pattern) I think we're on the right track.

Given these changes though, the current Expressions doc for Hoon makes little sense.  We have two options:

(1) Rewrite it so it makes sense, or

(2) Delete it.

As it stands, this doc is quite sloppy about the distinction between a Hoon source expression and the result of parsing the expression into an AST node.  There's little point in revising the doc so that it's just about expressions; the Syntax page handles those.  Do we want a page about AST nodes?  These are mentioned a bit in the Concepts page.  How much does a Hoon beginner really need to know about AST stuff?

In the interest of avoiding beginner concept overload, I vote deletion for this page.  About the only way it would make sense to save it is to turn it into a "compiler" page, where we go through parsing with `ream` and then `mint:ut`.  But a rewrite that drastic is tantamount to deletion anyway.

Are there reasons to keep this page?  If so, what exactly is the objective?  (At the very least, clarifying what the goal of this doc is a must.)

**Comment by cgyarvin** [comment]
Yes.  I’ve been through so much terminology on this issue...
