### ISSUE TITLE
No digraph pronunciation guidelines

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit.org#864]
`++` is pronounced `slus` instead of `luslus`. Apparently there's more irregular ones. These should all be documented, for as far as we want to insist they still exist. See also urbit/urbit#593.

**Comment by joshuareagan** [comment]
It would also be good to know if any of the irregular pronunciations are changing with the latest Hoon updates.

**Comment by joshuareagan** [comment]
For the record:

```
--    hephep    phep
+-    lushep    slep
++    luslus    slus
==    tistis    stet
+<    lusgal    glus
+>    lusgar    gras
-<    hepgal    gelp
->    hepgar    garp
```

**Comment by Fang-** [comment]
Wasn't the whole idea behind the new and """improved""" pronouncables to make them faster to say repetitively? (^:

I agree there's no real need for special pronunciations here. Even `slus` I hear used very rarely.

~~The lark ones might just want special lark pronunciation instead, higher or lower pitched grunts for left and right respectively.~~
