### ISSUE TITLE
Eternal nest fail help

### ISSUE THREAD

**Issue by mikolajpp** [urbit/urbit.org#871]
It seems dabbling at frontend for far too long and I forgot some crucial parts of Hoon.
We have this little snippet (best used wit plato!):

```
!:

=/  a  (mule |.((ream '(add 2 2')))
    ?:  -.a
    'No syntax error'
    ?~  p.a
    'Empty list'
    p.a
```

I know that in case of parser failure p.a is a list of tanks (a tang). But it seems compiler knows better. 
No matter how many checks I put in, it always fails with nest-fail. I am correctly dispatching on failure flag with `?:`. Then prove that list is non-empty with `?~`. What is missing?

**Comment by cgyarvin** [comment]
Yeah, tanks are tanks because they are simple as hell and you can hack the hell them.  There will be better ways to do all this.

I’m starting to actually want to use this thing of yours!  Will it let me use vim (or at least neovim)?

**Comment by mikolajpp** [comment]
@cgyarvin , I would very much prefer ++ut having a rewrite. 

Plato has inflated to 400 lines half of which is re-parsing of errors.

So what's the editor you are using right now? It would be cool for plato to gain another frontend - provided it is possible to hook whatever you are using right into plato via HTTP requests
