### ISSUE TITLE
canonical definition of "Urbit"

### ISSUE THREAD

**Issue by joshuareagan** [urbit/urbit.org#874]
There are a number of distinct definitions of "Urbit" in the documentation, and I'm wondering which of these is the preferred one.  It can be (1) the clean-slate software stack, (2) the P2P network of personal servers; or we sometimes say (3) each personal server is "an urbit" (usually lowercase?).  Are there others?

The third definition is fairly distinct from the first two, and if we lowercase it that should be enough to distinguish it.  So mainly I'm asking which of the first two is strictly more correct.  I'm rewriting the technical overview and I'm trying to destroy all the ambiguity I can.

Please be patient with me, I have ~~autism~~ a philosophy degree.

**Comment by ohAitch** [comment]
I think canonically they're "Urbit", "the Urbit network", and "an Urbit"
respectively; people certainly use "Facebook"(the software system) vs "a
Facebook"(digital identity running in that software system) in this way.
And the network is just the set of Urbits(3, as instantiations of 1) you
can see.

**Comment by rmariani** [comment]
It's muddled, you're right. We hear both "Urbit is a clean-slate software stack" and "Urbit is a virtual city of general-purpose personal servers." 

Maybe because (1) doesn't mean much without (2) and vice versa. In my humble opinion, (1) should be the dominant usage for the purposes of a technical overview, because the new software stack is where all the technical meat lives. The P2P network is more on the "product" side of the spectrum.

**Comment by cgyarvin** [comment]
I have been very insistent on the lower case for an urbit, the thing

**Comment by joshuareagan** [comment]
Okay, that's pretty clear.  Thanks guys.

**Comment by cgyarvin** [comment]
The idea of “the” subject is a common illusion inherited from old-fashioned “environments.”  Any noun can be used as a subject.  

Your expressions in the dojo use a subject which the dojo builds, out of shell variables and other state, on top of the kernel subject that  %gall passes it.  All this state, at rest, is formal state and reproducible from events.

I’d

**Comment by cgyarvin** [comment]
The stack frames in a computation are *not* formal state.  The programmer has no way to access this data introspectively.
