### ISSUE TITLE
Commentary in source code of standard library documentation

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit.org#875]
Each entry in the standard library documentation has an accompanying block of its hoon.hoon source. From hoon.hoon it inherited an uneven pattern of code commentary. 

For example: 
```
++  gte
  ~/  %gte
  :>    unsigned greater than or equals
  :>
  :>  returns whether {a >= b}.
  :>
  :>  a: left hand operand (todo: name)
  :>  b: right hand operand
  |=  [a=@ b=@]
  :>  greater than or equal to?
  ^-  ?
  !(lth a b)
::
```

No code commentary can be seen for `++gte` in  [basic arithmetic](https://urbit.org/docs/hoon/library/1a/) doc, though. This is typical for all the standard library docs. Maybe that's intentional, to make things bite-sized. Or because some of this commentary is redundant with regard to the explanation that is already given in the library. Or perhaps it's that hoon.hoon has been updated with more commentary since then.

So what should be philosophy of source commentary?  My instincts tell me that the obvious approach is to comment the code only where something would benefit from being clarified. However, this would result in standard library documents that take considerably longer to update/write.

Side note: It seems that `:>` is deprecated. Ted introduced me to a new method of leading commentary that can be seen in the [turbo-ford branch](https://github.com/urbit/arvo/blob/ford-turbo/lib/ford-turbo.hoon).

**Comment by cgyarvin** [comment]
Confirm what Keaton says here.
