### ISSUE TITLE
Heading legibility in hoon std lib docs

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/urbit.org#876]
I don't think 'Accepts', 'Produces' and 'Source' should be set in H2.

Instead I'd like to suggest that the description of the op should be like the rune docs, which look great.

I think this is best because it makes it easier to scan the page to find what you're looking for.

**Comment by rmariani** [comment]
I am inclined to agree with this, it looks weird having the 'Accepts' etc so large.
