### ISSUE TITLE
Mixed Content Warning in Firefox 52.0.1

### ISSUE THREAD

**Issue by Peregrine42** [urbit/urbit.org#9]
Hi Urbit,

When I visit `https://urbit.org`, I get a warning from Firefox that my connection is not secure.
I've spent a little time looking into the issue, and it seems that image content coming from `media.urbit.org` is not using SSL. This causes Firefox to issue a warning that some parts of the site are using HTTP, when the user requested an HTTPS connection.

That is my best guess at the cause - I hope you can arrange an easy fix.
I am sorry if this is not the correct channel for reporting bugs with the site - just let me know and I shall close this and re-raise on the correct channel.

Also, thank you for creating an amazing and inspiring project!

Thanks,
peregrine42

**Comment by galenwp** [comment]
Hello!  Thanks!  This is the correct channel, and I think I know what's going on.  Our images are hosted on GCP, and I think there is (or was, when we set this up) some problem with custom certificates.  

Anyway, I'll look into this again and report back.

**Comment by Peregrine42** [comment]
Thank you very much! Great response!
