### ISSUE TITLE
Dates should have single-digit days and months

### ISSUE THREAD

**Issue by flowerornament** [urbit/urbit.org#90]
<img width="542" alt="Screenshot 2019-05-17 15 34 44" src="https://user-images.githubusercontent.com/31774/57959589-6462f300-78b9-11e9-9593-649100c2457f.png">

Urbit dates use single digit days and months, so this timestamp should be `~2019.5.17`.

**Comment by Fang-** [comment]
(See also urbit/arvo#1065 and post your thoughts!)

**Comment by hardcodepunk** [comment]
Zola doesn't compile if dates are single-digit. I get the dates dynamically out of the metadata of the posts too.

**Comment by flowerornament** [comment]
@friederjanmoerman if there's really no way to reformat it, let's change the date formatting so they don't look like Arvo dates. I'd go with `2019-05-17`.

**Comment by flowerornament** [comment]
Removed dates for now
