### ISSUE TITLE
Arvo docs URL in Azimuth document proposal 404's

### ISSUE THREAD

**Issue by bencalder** [urbit/urbit.org#915]
The broken URL: https://urbit.org/docs/arvo/internals/

The proposal can be found [here](https://github.com/urbit/azimuth/blob/644157d76072271501c5427f427fbe8d0eb08903/proposals/0xcb1f81e42b5e75f000f94fc71a3ea70cab4bfc6f236b91e717f1b9516e5596b5.txt#L1), but it's much easier to read in the [commit](https://github.com/urbit/azimuth/commit/644157d76072271501c5427f427fbe8d0eb08903).

**Comment by Fang-** [comment]
Good catch. Docs should continue to serve something on that URL, even if it's just a redirect to the new location.
