### ISSUE TITLE
sample bunts should be documented along with traversal gates

### ISSUE THREAD

**Issue by mattnewport** [urbit/urbit.org#940]
The left and right fold functions `roll` and `reel` use the bunt value for their accumulator. For some functions like product rather than sum it would be useful to have variants that take an initial value (1 rather than 0) for the accumulator. This is common in other languages but I don't see a way to do this with the current Hoon standard library.

**Comment by tinnus-napbus** [comment]
examples of specifying initial values using `|:` have been added to the docs for these two functions
