### ISSUE TITLE
Primer section titles should be title case

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit.org#95]
Ideally we would do something like:

**Aegean: What Urbit is for**

As opposed to:

**aegean: what urbit is for**

See attached screenshot. This appears in the blue inset table of contents, the menu, and the headers themselves.

<img width="895" alt="Screen Shot 2019-05-21 at 3 30 36 PM" src="https://user-images.githubusercontent.com/1467211/58134983-8fad5100-7bdd-11e9-8d1c-c6dfee496dfc.png">

**Comment by hardcodepunk** [comment]
Solved issue in `general-bug-fixes` branch.
