### ISSUE TITLE
[email protected] in primer menu

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit.org#96]
See attached screenshot. This doesn't seem to be an issue in the menu in other places — but on the primer the email is somehow redacted.

<img width="895" alt="Screen Shot 2019-05-21 at 3 32 17 PM" src="https://user-images.githubusercontent.com/1467211/58135026-b2d80080-7bdd-11e9-902e-1c1328446c55.png">

**Comment by hardcodepunk** [comment]
This doesn't seem to be an issue anymore.

**Comment by matildepark** [comment]
I still see it? https://urbit.org/primer/

![image](https://user-images.githubusercontent.com/20846414/60404578-363f2700-9b78-11e9-81cc-c3c1bd9e7649.png)

**Comment by hardcodepunk** [comment]
Ah, I overlooked we were talking about the one in the footer. You can find the fix in the `general-bug-fixes` branch.
