### ISSUE TITLE
Consistent styling of unordered and ordered lists …

### ISSUE THREAD

**Issue by ghost** [urbit/urbit.org#985]
Having read through the docs, I wondered if ordered lists should use the same styling as unordered lists, i.e. “indentation” via margin and/or padding on the left side.

Seems the only occasion of `<ol>` and `;ol;` in the docs is in [Sail and Udon](https://urbit.org/docs/tutorials/sail-and-udon/) (or [sail-and-udon.md](https://github.com/urbit/docs/blob/master/tutorials/sail-and-udon.md) respectively). That’s also where I first realised this issue as the “indentation” of the `<ol>` output compared to the `<ul>` output really confused me in regards of Udon syntax.

<img width="431" alt="Screenshot 2020-03-16 at 18 13 28" src="https://user-images.githubusercontent.com/62216503/76784568-2920a180-67b4-11ea-938e-698d6cc53dcd.png">

The `<ul>` has some custom properties as well as some classes:

```
.mb4, body.docs article ul {
    margin-bottom: 2rem;
}

.mt3, body.docs article ul {
    margin-top: 1rem;
}

ul {
    margin-block-start: 0;
    margin-block-end: 0;
    padding-inline-start: 0;
    padding-inline-end: 0;
}
```

Maybe the same styling could and should be applied to `<ol>`?

**Comment by matildepark** [comment]
No longer relevant.
