### ISSUE TITLE
HTML title never displays any information except "Urbit"

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit.org#99]
"Urbit" is the only text that will ever display on the HTML title tab, no matter where you are on the website. It should display the page's title. 

<img width="209" alt="Screen Shot 2019-05-22 at 5 51 05 PM" src="https://user-images.githubusercontent.com/10265578/58218116-a70e3c00-7cba-11e9-8bed-62cde123b208.png">

**Comment by matildepark** [comment]
@msutherl This can be closed now, too.
