### ISSUE TITLE
Hoon tutorial 2.5: type polymorphism examples no longer use +*

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#993]
In `docs/tutorials/hoon/type-polymorphism.md`, under "Parametric Polymorphism and +* Arms", `set`, `tree`, and `list` are given as examples of arms defined with `+*`. However, they've recently been rewritten to utilize the `|$` rune instead to implement polymorphism. Besides documenting the `|$` rune (a current item on my to-do list), this section needs to be rewritten somehow to reflect these changes.

**Comment by tinnus-napbus** [comment]
hoon school has now been fully rewritten
